In [1]:
import torch
assert torch.cuda.is_available(), "Turn on a GPU: Runtime → Change runtime type → T4 GPU, then restart."
print(torch.cuda.get_device_name(0))

Tesla T4

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os, re
if "COLAB_" not in "".join(os.environ.keys()):
    !pip install unsloth
else:
    import torch
    v = re.match(r"[\d]{1,}\.[\d]{1,}", str(torch.__version__)).group(0)
    xformers = "xformers==" + {"2.10": "0.0.34", "2.9": "0.0.33.post1", "2.8": "0.0.32.post2"}.get(v, "0.0.34")
    !pip install sentencepiece protobuf "datasets==4.3.0" "huggingface_hub>=0.34.0" hf_transfer
    !pip install --no-deps unsloth_zoo bitsandbytes accelerate {xformers} peft trl triton unsloth
    !pip install --no-deps --upgrade "torchao>=0.16.0"
!pip install transformers==4.56.2
!pip install --no-deps trl==0.22.2

Requirement already satisfied: sentencepiece in /usr/local/lib/python3.13/dist-packages (0.2.2)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (5.29.6)
Collecting datasets==4.3.0
  Downloading datasets-4.3.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: huggingface_hub>=0.34.0 in /usr/local/lib/python3.13/dist-packages (1.29.0)
Collecting hf_transfer
  Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (3.32.5)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (2.1.3)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (23.0.1)
Collecting dill<0.4.1,>=0.3.0 (from datasets==4.3.0)
  Downloading dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (2.2.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (4.0.1)
Collecting multiprocess<0.70.17 (from datasets==4.3.0)
  Downloading multiprocess-0.70.16-py312-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2025.9.0,>=2023.1.0 (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0)
  Downloading fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from datasets==4.3.0) (6.0.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0) (1.6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.13/dist-packages (from huggingface_hub>=0.34.0) (4.16.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (3.14.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets==4.3.0) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets==4.3.0) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets==4.3.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets==4.3.0) (3.19)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets==4.3.0) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets==4.3.0) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets==4.3.0) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets==4.3.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets==4.3.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datasets==4.3.0) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0) (1.24.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==4.3.0) (1.17.0)
Downloading datasets-4.3.0-py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 22.6 MB/s eta 0:00:00
Downloading hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 53.2 MB/s eta 0:00:00a 0:00:01
Downloading dill-0.4.0-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 7.6 MB/s eta 0:00:00
Downloading fsspec-2025.9.0-py3-none-any.whl (199 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 16.9 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py312-none-any.whl (146 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.7/146.7 kB 9.1 MB/s eta 0:00:00
Installing collected packages: hf_transfer, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.12.0
    Uninstalling fsspec-2025.12.0:
      Successfully uninstalled fsspec-2025.12.0
  Attempting uninstall: dill
    Found existing installation: dill 0.4.1
    Uninstalling dill-0.4.1:
      Successfully uninstalled dill-0.4.1
  Attempting uninstall: multiprocess
    Found existing installation: multiprocess 0.70.19
    Uninstalling multiprocess-0.70.19:
      Successfully uninstalled multiprocess-0.70.19
  Attempting uninstall: datasets
    Found existing installation: datasets 4.8.5
    Uninstalling datasets-4.8.5:
      Successfully uninstalled datasets-4.8.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.9.0 which is incompatible.
Successfully installed datasets-4.3.0 dill-0.4.0 fsspec-2025.9.0 hf_transfer-0.1.9 multiprocess-0.70.16

Collecting unsloth_zoo
  Downloading unsloth_zoo-2026.9.5-py3-none-any.whl.metadata (33 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.13/dist-packages (1.14.0)
Collecting xformers==0.0.34
  Downloading xformers-0.0.34-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.13/dist-packages (0.20.0)
Collecting trl
  Downloading trl-1.13.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: triton in /usr/local/lib/python3.13/dist-packages (3.6.0)
Collecting unsloth
  Downloading unsloth-2026.9.6-py3-none-any.whl.metadata (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.0/81.0 kB 8.9 MB/s eta 0:00:00
Downloading xformers-0.0.34-cp39-abi3-manylinux_2_28_x86_64.whl (110.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.8/110.8 MB 8.3 MB/s eta 0:00:00:00:0100:01
Downloading unsloth_zoo-2026.9.5-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 86.9 MB/s eta 0:00:00
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 27.8 MB/s eta 0:00:00:00:0100:01
Downloading trl-1.13.0-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 52.5 MB/s eta 0:00:00
Downloading unsloth-2026.9.6-py3-none-any.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 68.2 MB/s eta 0:00:00:00:0100:01
Installing collected packages: xformers, unsloth_zoo, unsloth, trl, bitsandbytes
Successfully installed bitsandbytes-0.50.2 trl-1.13.0 unsloth-2026.9.6 unsloth_zoo-2026.9.5 xformers-0.0.34
Collecting torchao>=0.16.0
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 76.2 MB/s eta 0:00:00:00:01
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.18.0
Collecting transformers==4.56.2
  Downloading transformers-4.56.2-py3-none-any.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.1/40.1 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (3.32.5)
Collecting huggingface-hub<1.0,>=0.34.0 (from transformers==4.56.2)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (2.1.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (2.32.4)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==4.56.2)
  Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.13/dist-packages (from transformers==4.56.2) (4.67.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.56.2) (2025.9.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.56.2) (1.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.56.2) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->transformers==4.56.2) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->transformers==4.56.2) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->transformers==4.56.2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->transformers==4.56.2) (2026.7.22)
Downloading transformers-4.56.2-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 97.1 MB/s eta 0:00:00:00:010:01
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 39.3 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 120.8 MB/s eta 0:00:00
Installing collected packages: huggingface-hub, tokenizers, transformers
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.29.0
    Uninstalling huggingface_hub-1.29.0:
      Successfully uninstalled huggingface_hub-1.29.0
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.23.1
    Uninstalling tokenizers-0.23.1:
      Successfully uninstalled tokenizers-0.23.1
  Attempting uninstall: transformers
    Found existing installation: transformers 5.16.1
    Uninstalling transformers-5.16.1:
      Successfully uninstalled transformers-5.16.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth 2026.9.6 requires structlog>=24.1.0, which is not installed.
unsloth 2026.9.6 requires tyro, which is not installed.
unsloth-zoo 2026.9.5 requires cut_cross_entropy; python_version >= "3.10" and (sys_platform != "darwin" or platform_machine != "arm64"), which is not installed.
unsloth-zoo 2026.9.5 requires msgspec, which is not installed.
unsloth-zoo 2026.9.5 requires tyro; sys_platform != "darwin" or platform_machine != "arm64", which is not installed.
unsloth 2026.9.6 requires trl!=0.19.0,<=0.24.0,>=0.18.2, but you have trl 1.13.0 which is incompatible.
trl 1.13.0 requires datasets>=4.7.0, but you have datasets 4.3.0 which is incompatible.
diffusers 0.40.0 requires huggingface-hub<2.0,>=1.23.0, but you have huggingface-hub 0.36.2 which is incompatible.
gradio 6.26.0 requires huggingface-hub<2.0,>=1.16.0, but you have huggingface-hub 0.36.2 which is incompatible.
Successfully installed huggingface-hub-0.36.2 tokenizers-0.22.2 transformers-4.56.2
Collecting trl==0.22.2
  Downloading trl-0.22.2-py3-none-any.whl.metadata (11 kB)
Downloading trl-0.22.2-py3-none-any.whl (544 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 544.8/544.8 kB 38.5 MB/s eta 0:00:00
Installing collected packages: trl
  Attempting uninstall: trl
    Found existing installation: trl 1.13.0
    Uninstalling trl-1.13.0:
      Successfully uninstalled trl-1.13.0
Successfully installed trl-0.22.2

In [4]:
from pathlib import Path
from google.colab import drive

root = Path("/content/drive/MyDrive")
hits = [p for p in root.rglob("training_export") if p.is_dir()]
if hits:
    for folder in hits:
        print("FOUND", folder)
        for child in sorted(folder.iterdir()):
            print(" ", child.name)
else:
    print("training_export not found. Top of My Drive:")
    for child in sorted(root.iterdir()):
        print(" ", child.name)

FOUND /content/drive/MyDrive/training_export
  _qa_dataset_scan.py
  _qa_nb_dump
  training_export
FOUND /content/drive/MyDrive/training_export/training_export
  manifest.json
  pdfplumber_train_batch_001.jsonl
  pdfplumber_train_batch_002.jsonl
  pdfplumber_train_batch_003.jsonl
  pdfplumber_train_batch_004.jsonl
  pdfplumber_train_batch_005.jsonl
  pdfplumber_train_batch_006.jsonl
  pdfplumber_train_batch_007.jsonl
  pdfplumber_train_batch_008.jsonl
  pdfplumber_train_batch_009.jsonl
  pdfplumber_train_batch_010.jsonl
  pdfplumber_train_batch_011.jsonl
  pdfplumber_val.jsonl
  tesseract_test.jsonl

In [7]:
import json
from pathlib import Path

data_path = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_001.jsonl")
assert data_path.exists(), data_path

rows = []
with data_path.open(encoding="utf-8") as fh:
    for line in fh:
        rows.append(json.loads(line))

methods = {row.get("ocr_method") for row in rows}
missing = sum(1 for row in rows if not (row.get("ocr_text") or "").strip() or not row.get("gemini_json"))
print("file", data_path.name)
print("rows", len(rows))
print("methods", methods)
print("missing text or json", missing)
print("keys", sorted(rows[0].keys()))

file pdfplumber_train_batch_001.jsonl
rows 5000
methods {'pdfplumber'}
missing text or json 0
keys ['blob_path', 'gemini_json', 'ocr_method', 'ocr_text', 'vendor']

In [8]:
INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)

examples = []
for row in rows:
    ocr = row["ocr_text"].strip()
    label = json.dumps(row["gemini_json"], ensure_ascii=False)
    examples.append({
        "blob_path": row["blob_path"],
        "conversations": [
            {"role": "user", "content": INSTRUCTION + "\n\nOCR text:\n" + ocr},
            {"role": "assistant", "content": label},
        ],
    })

ocr_chars = [len(ex["conversations"][0]["content"]) for ex in examples]
label_chars = [len(ex["conversations"][1]["content"]) for ex in examples]
print("examples", len(examples))
print("ocr chars  min", min(ocr_chars), "median", sorted(ocr_chars)[len(ocr_chars)//2], "max", max(ocr_chars))
print("json chars min", min(label_chars), "median", sorted(label_chars)[len(label_chars)//2], "max", max(label_chars))
print("label starts with", examples[0]["conversations"][1]["content"][:40])

examples 5000
ocr chars  min 116 median 5825 max 35611
json chars min 794 median 1823 max 27601
label starts with {"invoice_summary": {"irn": "", "tax": n

In [9]:
from unsloth import FastLanguageModel

max_seq_length = 8192
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=max_seq_length,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)
print("loaded Qwen2.5-1.5B with LoRA", max_seq_length)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2026.9.6: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth 2026.9.6 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

loaded Qwen2.5-1.5B with LoRA 8192

In [ ]:
from datasets import Dataset

def to_text(batch):
    texts = [
        tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False)
        for convo in batch["conversations"]
    ]
    return {"text": texts}

dataset = Dataset.from_list(examples)
dataset = dataset.map(to_text, batched=True)

def fits(example):
    n = len(tokenizer(example["text"], add_special_tokens=False)["input_ids"])
    return n <= max_seq_length

before = len(dataset)
dataset = dataset.filter(fits)
print("kept", len(dataset))
print("dropped_too_long", before - len(dataset))

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

kept 4483
dropped_too_long 517

In [ ]:
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=8192,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)
max_seq_length = 8192

dataset = Dataset.from_list(examples).map(to_text, batched=True)
before = len(dataset)
dataset = dataset.filter(fits)
print("kept", len(dataset))
print("dropped_too_long", before - len(dataset))

==((====))==  Unsloth 2026.9.5: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

In [ ]:
from pathlib import Path
p = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_001.jsonl")
print("drive mounted", Path("/content/drive/MyDrive").exists())
print("batch file exists", p.exists())

drive mounted True
batch file exists True

In [ ]:
from trl import SFTTrainer, SFTConfig
from unsloth import is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only

train_dataset = dataset.remove_columns(
    [c for c in dataset.column_names if c != "text"]
)

ckpt_dir = "/content/drive/MyDrive/invoice_lora_checkpoints"
trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=train_dataset,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    packing=False,
    args=SFTConfig(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=2e-4,
        warmup_steps=10,
        logging_steps=10,
        save_strategy="steps",
        save_steps=50,
        save_total_limit=2,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir=ckpt_dir,
        report_to="none",
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)

stats = trainer.train()
print(stats)

save_dir = "/content/drive/MyDrive/invoice_lora"
model.save_pretrained(save_dir)
tokenizer.save_pretrained(save_dir)
print("saved", save_dir)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/4483 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

Map:   0%|          | 0/4483 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 4,483 | Num Epochs = 1 | Total steps = 561
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

TrainOutput(global_step=561, training_loss=0.03628432002489633, metrics={'train_runtime': 2146.0206, 'train_samples_per_second': 2.089, 'train_steps_per_second': 0.261, 'total_flos': 1.4462608484582093e+17, 'train_loss': 0.03628432002489633, 'epoch': 1.0})
saved /content/drive/MyDrive/invoice_lora

In [ ]:
import json
from pathlib import Path

FastLanguageModel.for_inference(model)

val_path = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl")
checked = 0
with val_path.open(encoding="utf-8") as fh:
    for line in fh:
        row = json.loads(line)
        gold = row["gemini_json"]["invoice_summary"]
        prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
        inputs = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt",
        ).to(model.device)
        if inputs.shape[-1] > 6000:
            continue
        out = model.generate(
            input_ids=inputs,
            max_new_tokens=800,
            do_sample=False,
            use_cache=True,
        )
        text = tokenizer.decode(out[0][inputs.shape[-1]:], skip_special_tokens=True)
        try:
            pred = json.loads(text[text.find("{") : text.rfind("}") + 1])
            summary = pred.get("invoice_summary") or {}
        except Exception:
            print("---")
            print("JSON parse failed")
            print(text[:300])
            checked += 1
            if checked >= 5:
                break
            continue
        print("---")
        for key in ("invoice_no", "vendor_gstin", "customer_gstin", "total"):
            print(key, summary.get(key), "vs", gold.get(key))
        checked += 1
        if checked >= 5:
            break
print("checked", checked)

The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.

---
JSON parse failed
{"invoice_summary": {"irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c", "tax": "405.34", "total": "8512.00", "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.", "customer": "ASTER G MADEGOWDA PHARMA", "invoice_no": "B159643", "invoice_date": "2025-12-22", "vendor_gstin": "29A
---
invoice_no B162811 vs B162811
vendor_gstin 29AACCD7912K1ZD vs 29AACCD7912K1ZD
customer_gstin 29AAFCH9013A1ZV vs 29AACCD7912K1ZD
total 1463.00 vs 1463.00
---
JSON parse failed
{"invoice_summary": {"irn": "d63c48e74813cd5ddce107d56dc2dda3e9fe00de1d515502a162e636a70cac18", "tax": "59.44", "total": "1248.00", "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.", "customer": "ASTER G MADEGOWDA PHARMA", "invoice_no": "B165133", "invoice_date": "2025-12-22", "vendor_gstin": "29AA
---
JSON parse failed
{"invoice_summary": {"irn": "59712b2d3349b9dcff202e62fc12e8083b785fd12211bf3370f87bf70d53fbd9", "tax": "80.78", "total": "210538.17", "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.", "customer": "ASTER G MADEGOWDA PHARMA", "invoice_no": "B165887", "invoice_date": "2025-12-22", "vendor_gstin": "29
---
invoice_no B166447 vs B166447
vendor_gstin 29AACCD7912K1ZD vs 29AACCD7912K1ZD
customer_gstin 29AAFCH9013A1ZV vs 29AACCD7912K1ZD
total 2909.84 vs 3055.00
checked 5

In [ ]:
import json
from pathlib import Path

FastLanguageModel.for_inference(model)

val_path = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl")
seen = set()
shown = 0

with val_path.open(encoding="utf-8") as fh:
    for line in fh:
        row = json.loads(line)
        vendor = (row.get("vendor") or "").strip() or "UNKNOWN"
        if vendor in seen:
            continue
        prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
        inputs = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=True,
            add_generation_prompt=True,
            return_tensors="pt",
        ).to(model.device)
        if inputs.shape[-1] > 6000:
            continue
        seen.add(vendor)
        out = model.generate(
            input_ids=inputs,
            attention_mask=inputs.ne(tokenizer.pad_token_id),
            max_new_tokens=4096,
            do_sample=False,
            use_cache=True,
        )
        text = tokenizer.decode(out[0][inputs.shape[-1]:], skip_special_tokens=True)
        print("=" * 80)
        print("vendor", vendor)
        print("blob", row["blob_path"])
        print("--- model ---")
        print(text)
        print("--- gemini ---")
        print(json.dumps(row["gemini_json"], ensure_ascii=False, indent=2))
        shown += 1
        if shown >= 3:
            break

print("shown", shown)

================================================================================
vendor HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.
blob POD/20260330091052_vekrxjeq/ZYDUS_E-INVOICE_-_GMH_-_MARCH_26/Splitted/Invoices/invoice_B159643.pdf
--- model ---
{"invoice_summary": {"irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c", "tax": "405.34", "total": "8512.00", "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.", "customer": "ASTER G MADEGOWDA PHARMA", "invoice_no": "B159643", "invoice_date": "2025-12-22", "vendor_gstin": "29AACCD7912K1ZD", "customer_gstin": "29AAFCH9013A1ZV", "customer_address": "#76/1,2nd & 3rd FLOOR,ARUNA\n#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nMALAVALLI MADURU ROAD BHARATHDI aNtA"}, "line_items": {"count": 5, "items": [{"hsn_code": "30049079", "quantity": "5", "sku_code": null, "unit_price": "264.22", "total_amount": "1294.68", "lot_batch_number": "IA00905A", "additional_fields": {"mfg": "ZYD", "mrp": "433.49", "expiry_date": "06-27", "free_quantity": "0"}, "product_description": ".ATORVA 80 TAB"}, {"hsn_code": "300490", "quantity": "1", "sku_code": null, "unit_price": "104.11", "total_amount": "102.03", "lot_batch_number": "IA01261A", "additional_fields": {"mfg": "ZYD", "mrp": "143.83", "expiry_date": "08-27", "free_quantity": "0"}, "product_description": ".DOXOLIN TAB"}, {"hsn_code": "30049069", "quantity": "5", "sku_code": null, "unit_price": "41.00", "total_amount": "200.90", "lot_batch_number": "TA1116A", "additional_fields": {"mfg": "ZYD", "mrp": "66.36", "expiry_date": "11-28", "free_quantity": "0"}, "product_description": ".NASOCLEAR NASAL SPRAY"}, {"hsn_code": "30049069", "quantity": "30", "sku_code": null, "unit_price": "221.40", "total_amount": "6509.16", "lot_batch_number": "IA01382B", "additional_fields": {"mfg": "ZYD", "mrp": "345.26", "expiry_date": "08-27", "free_quantity": "0"}, "product_description": ".NUCOXIA MR TAB"}, {"hsn_code": "", "quantity": "1", "unit_price": "104.11", "total_amount": "104.11", "lot_batch_number": "", "recovered_from_ocr": true, "product_description": "AZD"}], "title": "line items (with lot / batch)", "has_quantity_info": true, "has_lot_batch_info": true, "items_with_quantity": 5, "items_with_lot_batch": 4, "standardized_columns": {"discount": "discount", "hsn_code": "hsn/sac code", "quantity": "quantity", "sku_code": "sku/item code", "tax_amount": "tax %", "unit_price": "unit price", "total_amount": "total amount", "unit_of_measure": "unit of", "lot_batch_number": "lot/batch number", "additional_fields": "other detected fields", "product_description": "product/item description"}}}
--- gemini ---
{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-02-02",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nJ.C.RD , BANGALORE - 560002"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": "ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": "NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}
================================================================================
vendor K. ENTERPRISES
blob POD/20260408034308_xg1odlpf/E_Invoice/Splitted/Split_1/Invoices/invoice_KE_23919.pdf
--- model ---
{"invoice_summary": {"irn": "be7222f6a2f28694eebf465968fb45785037dd94df641979dd10298c96067558", "tax": null, "total": "30533.43", "vendor": "K. ENTERPRISES", "customer": "KOKILABEN DHIRUBHAI AMBani HOSPITAL", "invoice_no": "KE/23919", "invoice_date": "2026-03-02", "vendor_gstin": "27AAATM4557G1ZH", "customer_gstin": "27AAATM4557G1ZH", "customer_address": "MANDKE FOUNDATION , KOKILABEN DHIRUBHAI AMBan\nNEAR DAKC GATE NO.4 , THANE BELAPUR ROAD,\nNAVI MUMBAI, NAVI MUMBAI, - 400710."}, "line_items": {"count": 10, "items": [{"hsn_code": "30049039", "quantity": "30", "sku_code": null, "unit_price": "161.49", "total_amount": "4844.70", "lot_batch_number": "NSA5016", "additional_fields": {"mfg": "SAN", "mrp": "235.50", "expiry_date": "10/27", "free_quantity": "0"}, "product_description": "ALLEGRA SUSPENSION. 100ML"}, {"hsn_code": "30049079", "quantity": "20", "sku_code": null, "unit_price": "258.94", "total_amount": "5178.80", "lot_batch_number": "IA01944A", "additional_fields": {"mfg": "ZY", "mrp": "433.49", "expiry_date": "11/27", "free_quantity": "0"}, "product_description": "#ATORVA 80MG TABLETS"}, {"hsn_code": "30049099", "quantity": "20", "sku_code": null, "unit_price": "283.53", "total_amount": "5670.60", "lot_batch_number": "WBA5F030", "additional_fields": {"mfg": "TPL", "mrp": "437.49", "expiry_date": "06/28", "free_quantity": "0"}, "product_description": "CARNISURE 500MG TAB"}, {"hsn_code": "30049099", "quantity": "3", "sku_code": null, "unit_price": "198.18", "total_amount": "594.54", "lot_batch_number": "BABF0010", "additional_fields": {"mfg": "TPL", "mrp": "306.00", "expiry_date": "08/28", "free_quantity": "0"}, "product_description": "CARNISURE SYRUP 30ML"}, {"hsn_code": "30049099", "quantity": "7", "sku_code": null, "unit_price": "198.18", "total_amount": "1387.26", "lot_batch_number": "BABF0012", "additional_fields": {"mfg": "TPL", "mrp": "306.00", "expiry_date": "08/28", "free_quantity": "0"}, "product_description": "CARNISURE SYRUP 30ML"}, {"hsn_code": "30045090", "quantity": "5", "sku_code": null, "unit_price": "254.85", "total_amount": "1274.25", "lot_batch_number": "A869", "additional_fields": {"mfg": "GSK", "mrp": "561.56", "expiry_date": "07/27", "free_quantity": "0"}, "product_description": "CCM TABLETS (40S)"}, {"hsn_code": "30043913", "quantity": "100", "sku_code": null, "unit_price": "7.98", "total_amount": "798.00", "lot_batch_number": "NA00382A", "additional_fields": {"mfg": "ZY", "mrp": "10.87", "expiry_date": "04/27", "free_quantity": "0"}, "product_description": "DEXONA INJECTION 2ML"}, {"hsn_code": "30043990", "quantity": "10", "sku_code": null, "unit_price": "69.16", "total_amount": "691.60", "lot_batch_number": "UA9A", "additional_fields": {"mfg": "ZY", "mrp": "114.03", "expiry_date": "10/27", "free_quantity": "0"}, "product_description": "#ELTROXIN 50MCG TABLETS"}, {"hsn_code": "300490", "quantity": "100", "sku_code": null, "unit_price": "18.28", "total_amount": "1828.00", "lot_batch_number": "MA03959A", "additional_fields": {"mfg": "ZY", "mrp": "564.61", "expiry_date": "08/27", "free_quantity": "0"}, "product_description": "METATOP NASAL SPRAY 12GM"}, {"hsn_code": "30049029", "quantity": "100", "sku_code": null, "unit_price": "18.28", "total_amount": "1828.00", "lot_batch_number": "FA00291A", "additional_fields": {"mfg": "ZY", "mrp": "53.70", "expiry_date": "09/27", "free_quantity": "0"}, "product_description": "#MONOTAX 500MG INJECTION"}], "title": "line items (with lot / batch)", "has_quantity_info": true, "has_lot_batch_info": true, "items_with_quantity": 10, "items_with_lot_batch": 10, "standardized_columns": {"discount": "discount", "hsn_code": "hsn/sac code", "quantity": "quantity", "sku_code": "sku/item code", "tax_amount": "tax %", "unit_price": "unit price", "total_amount": "total amount", "unit_of_measure": "unit of measure", "lot_batch_number": "lot/batch number", "additional_fields": "other detected fields", "product_description": "product/item description"}}}
--- gemini ---
{
  "invoice_summary": {
    "irn": "be7222f6a2f28694eebf465968fb45785037dd94df641979dd10298c96067558",
    "tax": "1453.99",
    "total": "30533.43",
    "vendor": "K. ENTERPRISES",
    "customer": "KOKILABEN DHIRUBHAI AMBANI HOSPITAL",
    "invoice_no": "KE/23919",
    "invoice_date": "2026-03-02",
    "vendor_gstin": "27AAATM4557G1ZH",
    "customer_gstin": "27AAATM4557G1ZH",
    "customer_address": "MANDKE FOUNDATION , KOKILABEN DHIRUBHAI AMBAN\nNEAR DAKC GATE NO.4 , THANE BELAPUR ROAD,\nNAVI MUMBAI, NAVI MUMBAI, - 400710."
  },
  "line_items": {
    "count": 11,
    "items": [
      {
        "hsn_code": "30049039",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "161.49",
        "total_amount": "4844.70",
        "lot_batch_number": "NSA5016",
        "additional_fields": {
          "mfg": "SAN",
          "mrp": "235.50",
          "expiry_date": "10/27",
          "free_quantity": "0"
        },
        "product_description": "ALLEGRA SUSPENSION. 100ML"
      },
      {
        "hsn_code": "30049079",
        "quantity": "20",
        "sku_code": null,
        "unit_price": "258.94",
        "total_amount": "5178.80",
        "lot_batch_number": "IA01944A",
        "additional_fields": {
          "mfg": "ZY",
          "mrp": "433.49",
          "expiry_date": "11/27",
          "free_quantity": "0"
        },
        "product_description": "#ATORVA 80MG TABLETS 10S"
      },
      {
        "hsn_code": "30049099",
        "quantity": "20",
        "sku_code": null,
        "unit_price": "283.53",
        "total_amount": "5670.60",
        "lot_batch_number": "WBA5F030",
        "additional_fields": {
          "mfg": "TPL",
          "mrp": "437.80",
          "expiry_date": "06/28",
          "free_quantity": "0"
        },
        "product_description": "CARNISURE 500MG TAB 10S"
      },
      {
        "hsn_code": "30049099",
        "quantity": "3",
        "sku_code": null,
        "unit_price": "198.18",
        "total_amount": "594.54",
        "lot_batch_number": "BABF0010",
        "additional_fields": {
          "mfg": "TPL",
          "mrp": "306.00",
          "expiry_date": "08/28",
          "free_quantity": "0"
        },
        "product_description": "CARNISURE SYRUP 30ML"
      },
      {
        "hsn_code": "30049099",
        "quantity": "7",
        "sku_code": null,
        "unit_price": "198.18",
        "total_amount": "1387.26",
        "lot_batch_number": "BABF0012",
        "additional_fields": {
          "mfg": "TPL",
          "mrp": "306.00",
          "expiry_date": "08/28",
          "free_quantity": "0"
        },
        "product_description": "CARNISURE SYRUP 30ML"
      },
      {
        "hsn_code": "30045090",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "254.85",
        "total_amount": "1274.25",
        "lot_batch_number": "A869",
        "additional_fields": {
          "mfg": "GSK",
          "mrp": "561.56",
          "expiry_date": "07/27",
          "free_quantity": "0"
        },
        "product_description": "CCM TABLETS (40S)"
      },
      {
        "hsn_code": "30043913",
        "quantity": "100",
        "sku_code": null,
        "unit_price": "7.98",
        "total_amount": "798.00",
        "lot_batch_number": "NA00382A",
        "additional_fields": {
          "mfg": "ZY",
          "mrp": "10.87",
          "expiry_date": "04/27",
          "free_quantity": "0"
        },
        "product_description": "DEXONA INJECTION 2ML"
      },
      {
        "hsn_code": "30043990",
        "quantity": "10",
        "sku_code": null,
        "unit_price": "69.16",
        "total_amount": "691.60",
        "lot_batch_number": "UA9A",
        "additional_fields": {
          "mfg": "GSK",
          "mrp": "114.03",
          "expiry_date": "10/27",
          "free_quantity": "0"
        },
        "product_description": "#ELTROXIN 50MCG TABLETS 120S"
      },
      {
        "hsn_code": "300490",
        "quantity": "10",
        "sku_code": null,
        "unit_price": "350.89",
        "total_amount": "3508.90",
        "lot_batch_number": "MA03959A",
        "additional_fields": {
          "mfg": "ZY",
          "mrp": "564.61",
          "expiry_date": "08/27",
          "free_quantity": "0"
        },
        "product_description": "METATOP NASAL SPRAY 12GM"
      },
      {
        "hsn_code": "30049029",
        "quantity": "100",
        "sku_code": null,
        "unit_price": "18.28",
        "total_amount": "1828.00",
        "lot_batch_number": "FA00291A",
        "additional_fields": {
          "mfg": "ZY",
          "mrp": "53.70",
          "expiry_date": "09/27",
          "free_quantity": "0"
        },
        "product_description": "#MONOTAX 500MG INJECTION"
      },
      {
        "hsn_code": "30045039",
        "quantity": "10",
        "sku_code": null,
        "unit_price": "330.28",
        "total_amount": "3302.80",
        "lot_batch_number": "SHC5010D",
        "additional_fields": {
          "mfg": "TPL",
          "mrp": "510.00",
          "expiry_date": "10/27",
          "free_quantity": "0"
        },
        "product_description": "SHELCAL CT MAX CAPSULES 15S"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 11,
    "items_with_lot_batch": 11,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}
================================================================================
vendor ARIHANT CHEMIST LLP.
blob POD/20260410132830_ogz5olam/SI_S_291029_04022026/Splitted/Invoices/invoice_S_291029.pdf
--- model ---
{"invoice_summary": {"irn": "8d24d564ecb48047db3009abb8ef07312e4fedb32bf65812f512bd7f03ec53cb", "tax": null, "total": "10777.42", "vendor": "ARIHANT CHEMIST LLP.", "customer": "POONA HOS MED STORE (UNIT OF RGCF)", "invoice_no": "S/291029", "invoice_date": "2026-02-04", "vendor_gstin": "27AAATR1097C2ZM", "customer_gstin": "27AAATR1097C2ZM", "customer_address": "GR. FLOOR SHOP AND BASEMENT, D WING, POONA HO OPP. CITY PRIDE MULTIPLEX PARVATI, PUNE - 411009. MAHARASHTRA - 27"}, "line_items": {"count": 2, "items": [{"hsn_code": "30049099", "quantity": "30", "sku_code": null, "unit_price": "125.33", "total_amount": "3759.90", "lot_batch_number": "IA01741A", "additional_fields": {"mfg": "ZIN", "mrp": "182.78", "expiry_date": "10/27", "free_quantity": "0"}, "product_description": "ZYCEL-100MG 10C-H STRIP"}, {"hsn_code": "3004", "quantity": "30", "sku_code": null, "unit_price": "216.81", "total_amount": "6504.30", "lot_batch_number": "IA01887B", "additional_fields": {"mfg": "ZIN", "mrp": "316.18", "expiry_date": "11/27", "free_quantity": "0"}, "product_description": "ZYCEL-200MG 10C(H) STRIP"}], "title": "line items (with lot / batch)", "has_quantity_info": true, "has_lot_batch_info": true, "items_with_quantity": 2, "items_with_lot_batch": 2, "standardized_columns": {"discount": "discount", "hsn_code": "hsn/sac code", "quantity": "quantity", "sku_code": "sku/item code", "tax_amount": "tax %", "unit_price": "unit price", "total_amount": "total amount", "unit_of_measure": "unit of measure", "lot_batch_number": "lot/batch number", "additional_fields": "other detected fields", "product_description": "product/item description"}}}
--- gemini ---
{
  "invoice_summary": {
    "irn": "8d24d564ecb48047db3009abb8ef07312e4fedb32bf65812f512bd7f03ec53cb",
    "tax": "513.22",
    "total": "10777.42",
    "vendor": "ARIHANT CHEMIST LLP.",
    "customer": "POONA HOS MED STORE (UNIT OF RGCF)",
    "invoice_no": "S/291029",
    "invoice_date": "2026-02-04",
    "vendor_gstin": "27AAATR1097C2ZM",
    "customer_gstin": "27AAATR1097C2ZM",
    "customer_address": "GR. FLOOR SHOP AND BASEMENT, D WING, POONA HO H.NO. 27+28/95, PROP. NO. P/2/24/00021000, NA NAVI PETH, PUNE - 411030."
  },
  "line_items": {
    "count": 2,
    "items": [
      {
        "hsn_code": "30049099",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "125.33",
        "total_amount": "3759.90",
        "lot_batch_number": "IA01741A",
        "additional_fields": {
          "mfg": "ZIN",
          "mrp": "182.78",
          "expiry_date": "10/27",
          "free_quantity": "0"
        },
        "product_description": "ZYCEL-100MG 10C-H"
      },
      {
        "hsn_code": "3004",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "216.81",
        "total_amount": "6504.30",
        "lot_batch_number": "IA01887B",
        "additional_fields": {
          "mfg": "ZIN",
          "mrp": "316.18",
          "expiry_date": "11/27",
          "free_quantity": "0"
        },
        "product_description": "ZYCEL-200MG 10C(H)"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 2,
    "items_with_lot_batch": 2,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}
shown 3

In [ ]:
import json, random, re
from pathlib import Path
from collections import defaultdict

if "FastLanguageModel" not in dir():
    from unsloth import FastLanguageModel
if "model" not in dir() or "tokenizer" not in dir():
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="unsloth/Qwen2.5-1.5B-Instruct",
        max_seq_length=8192,
        dtype=None,
        load_in_4bit=True,
    )
    model.load_adapter("/content/drive/MyDrive/invoice_lora")
FastLanguageModel.for_inference(model)

FIELDS = [
    "invoice_no", "invoice_date", "vendor", "customer",
    "vendor_gstin", "customer_gstin", "tax", "total", "irn",
]
KEY_FIELDS = ["invoice_no", "vendor_gstin", "customer_gstin", "total", "tax"]
MONEY = {"tax", "total"}

def norm(value):
    if value is None:
        return ""
    text = re.sub(r"\s+", " ", str(value)).strip().upper().replace(",", "")
    return "" if text in {"", "NONE", "NULL"} else text

def same(key, pred, gold):
    a, b = norm(pred), norm(gold)
    if key in MONEY and a and b:
        try:
            return abs(float(a) - float(b)) < 0.01
        except ValueError:
            return False
    return a == b

val_path = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl")
by_vendor = defaultdict(list)
with val_path.open(encoding="utf-8") as fh:
    for line in fh:
        row = json.loads(line)
        by_vendor[(row.get("vendor") or "UNKNOWN").strip().upper()].append(row)

rng = random.Random(7)
sample = []
for vendor in rng.sample(list(by_vendor), k=len(by_vendor)):
    picks = by_vendor[vendor][:]
    rng.shuffle(picks)
    sample.extend(picks[:2])
    if len(sample) >= 100:
        break
sample = sample[:100]

stats = {k: {"match": 0, "missing": 0, "wrong": 0, "gold_present": 0} for k in FIELDS}
stats["line_count"] = {"match": 0, "missing": 0, "wrong": 0, "gold_present": 0}
scored = 0
key_pass = 0

for row in sample:
    gold = row["gemini_json"]["invoice_summary"]
    gold_items = (row["gemini_json"].get("line_items") or {}).get("items") or []
    prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
    inputs = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to(model.device)
    if inputs.shape[-1] > 6000:
        continue
    out = model.generate(
        input_ids=inputs,
        attention_mask=inputs.ne(tokenizer.pad_token_id),
        max_new_tokens=2048,
        do_sample=False,
        use_cache=True,
    )
    text = tokenizer.decode(out[0][inputs.shape[-1]:], skip_special_tokens=True)
    summary, items = {}, []
    try:
        pred = json.loads(text[text.find("{") : text.rfind("}") + 1])
        summary = pred.get("invoice_summary") or {}
        items = (pred.get("line_items") or {}).get("items") or []
    except Exception:
        pass
    invoice_ok = True
    for key in FIELDS:
        g = gold.get(key)
        if not norm(g):
            continue
        stats[key]["gold_present"] += 1
        p = summary.get(key)
        if not norm(p):
            stats[key]["missing"] += 1
            ok = False
        elif same(key, p, g):
            stats[key]["match"] += 1
            ok = True
        else:
            stats[key]["wrong"] += 1
            ok = False
        if key in KEY_FIELDS and not ok:
            invoice_ok = False
    stats["line_count"]["gold_present"] += 1
    if not items:
        stats["line_count"]["missing"] += 1
    elif len(items) == len(gold_items):
        stats["line_count"]["match"] += 1
    else:
        stats["line_count"]["wrong"] += 1
    if invoice_ok:
        key_pass += 1
    scored += 1
    if scored % 10 == 0:
        print("scored", scored, flush=True)

total_match = sum(s["match"] for k, s in stats.items() if k != "line_count")
total_gold = sum(s["gold_present"] for k, s in stats.items() if k != "line_count") or 1
print("\nscored invoices", scored)
print(f"overall field accuracy {total_match / total_gold:.1%}")
print(f"invoices with invoice_no, both GSTINs, tax, and total all correct {key_pass / scored:.1%}")
print(f"\n{'field':<18} {'accuracy':>8} {'missing':>8} {'wrong':>7}")
rows = []
for key, s in stats.items():
    n = s["gold_present"] or 1
    rows.append((s["match"] / n, key, s))
for _, key, s in sorted(rows):
    n = s["gold_present"] or 1
    print(f"{key:<18} {s['match']/n:8.1%} {s['missing']/n:8.1%} {s['wrong']/n:7.1%}")

scored 10
scored 20

scored invoices 22
overall field accuracy 69.9%
invoices with invoice_no, both GSTINs, tax, and total all correct 18.2%

field              accuracy  missing   wrong
customer_gstin        36.4%     4.5%   59.1%
customer              50.0%     9.1%   40.9%
total                 68.2%     9.1%   22.7%
line_count            72.7%     9.1%   18.2%
vendor                72.7%     4.5%   22.7%
invoice_no            76.2%     4.8%   19.0%
vendor_gstin          77.3%     4.5%   18.2%
irn                   80.0%     0.0%   20.0%
tax                   80.0%    10.0%   10.0%
invoice_date          90.9%     4.5%    4.5%

In [ ]:
import json
from pathlib import Path
from datasets import Dataset
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only
from trl import SFTTrainer, SFTConfig

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)
max_seq_length = 8192

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora",
    max_seq_length=max_seq_length,
    dtype=None,
    load_in_4bit=True,
)
model.train()
trainable = 0
for name, param in model.named_parameters():
    if "lora_" in name:
        param.requires_grad = True
        trainable += param.numel()
print("trainable", trainable)
assert trainable > 0, "adapter did not load as trainable"

rows = []
path = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_002.jsonl")
with path.open(encoding="utf-8") as fh:
    for line in fh:
        row = json.loads(line)
        rows.append({
            "conversations": [
                {"role": "user", "content": INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()},
                {"role": "assistant", "content": json.dumps(row["gemini_json"], ensure_ascii=False)},
            ]
        })

def to_text(batch):
    return {"text": [
        tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False)
        for c in batch["conversations"]
    ]}

dataset = Dataset.from_list(rows).map(to_text, batched=True)
dataset = dataset.filter(
    lambda ex: len(tokenizer(ex["text"], add_special_tokens=False)["input_ids"]) <= max_seq_length
)
print("kept", len(dataset))
dataset = dataset.remove_columns([c for c in dataset.column_names if c != "text"])

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        packing=False,
        dataset_num_proc=1,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=1e-4,
        warmup_steps=10,
        logging_steps=10,
        save_strategy="steps",
        save_steps=50,
        save_total_limit=2,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir="/content/drive/MyDrive/invoice_lora_v2_checkpoints",
        report_to="none",
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)
print(trainer.train())
model.save_pretrained("/content/drive/MyDrive/invoice_lora_v2")
tokenizer.save_pretrained("/content/drive/MyDrive/invoice_lora_v2")
print("saved /content/drive/MyDrive/invoice_lora_v2")

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Unsloth 2026.9.4 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

trainable 18464768

Map:   0%|          | 0/5000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/5000 [00:00<?, ? examples/s]

kept 4686

Unsloth: Tokenizing ["text"]:   0%|          | 0/4686 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

Map:   0%|          | 0/4686 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 4,686 | Num Epochs = 1 | Total steps = 586
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

TrainOutput(global_step=586, training_loss=0.01949667776759981, metrics={'train_runtime': 2241.9366, 'train_samples_per_second': 2.09, 'train_steps_per_second': 0.261, 'total_flos': 1.5271700272036454e+17, 'train_loss': 0.01949667776759981, 'epoch': 1.0})
saved /content/drive/MyDrive/invoice_lora_v2

In [ ]:
import json, random, re
from pathlib import Path
from collections import defaultdict
from unsloth import FastLanguageModel

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora_v2",
    max_seq_length=8192,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

FIELDS = [
    "invoice_no", "invoice_date", "vendor", "customer",
    "vendor_gstin", "customer_gstin", "tax", "total", "irn",
]
KEY_FIELDS = ["invoice_no", "vendor_gstin", "customer_gstin", "total", "tax"]
MONEY = {"tax", "total"}

def norm(value):
    if value is None:
        return ""
    text = re.sub(r"\s+", " ", str(value)).strip().upper().replace(",", "")
    return "" if text in {"", "NONE", "NULL"} else text

def same(key, pred, gold):
    a, b = norm(pred), norm(gold)
    if key in MONEY and a and b:
        try:
            return abs(float(a) - float(b)) < 0.01
        except ValueError:
            return False
    return a == b

val_path = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl")
by_vendor = defaultdict(list)
with val_path.open(encoding="utf-8") as fh:
    for line in fh:
        row = json.loads(line)
        by_vendor[(row.get("vendor") or "UNKNOWN").strip().upper()].append(row)

rng = random.Random(7)
sample = []
for vendor in rng.sample(list(by_vendor), k=len(by_vendor)):
    picks = by_vendor[vendor][:]
    rng.shuffle(picks)
    sample.extend(picks[:2])
    if len(sample) >= 100:
        break
sample = sample[:100]

stats = {k: {"match": 0, "missing": 0, "wrong": 0, "gold_present": 0} for k in FIELDS}
stats["line_count"] = {"match": 0, "missing": 0, "wrong": 0, "gold_present": 0}
scored = 0
key_pass = 0

for row in sample:
    gold = row["gemini_json"]["invoice_summary"]
    gold_items = (row["gemini_json"].get("line_items") or {}).get("items") or []
    prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
    inputs = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to(model.device)
    if inputs.shape[-1] > 6000:
        continue
    out = model.generate(
        input_ids=inputs,
        attention_mask=inputs.ne(tokenizer.pad_token_id),
        max_new_tokens=2048,
        do_sample=False,
        use_cache=True,
    )
    text = tokenizer.decode(out[0][inputs.shape[-1]:], skip_special_tokens=True)
    summary, items = {}, []
    try:
        pred = json.loads(text[text.find("{") : text.rfind("}") + 1])
        summary = pred.get("invoice_summary") or {}
        items = (pred.get("line_items") or {}).get("items") or []
    except Exception:
        pass
    invoice_ok = True
    for key in FIELDS:
        g = gold.get(key)
        if not norm(g):
            continue
        stats[key]["gold_present"] += 1
        p = summary.get(key)
        if not norm(p):
            stats[key]["missing"] += 1
            ok = False
        elif same(key, p, g):
            stats[key]["match"] += 1
            ok = True
        else:
            stats[key]["wrong"] += 1
            ok = False
        if key in KEY_FIELDS and not ok:
            invoice_ok = False
    stats["line_count"]["gold_present"] += 1
    if not items:
        stats["line_count"]["missing"] += 1
    elif len(items) == len(gold_items):
        stats["line_count"]["match"] += 1
    else:
        stats["line_count"]["wrong"] += 1
    if invoice_ok:
        key_pass += 1
    scored += 1
    if scored % 10 == 0:
        print("scored", scored, flush=True)

total_match = sum(s["match"] for k, s in stats.items() if k != "line_count")
total_gold = sum(s["gold_present"] for k, s in stats.items() if k != "line_count") or 1
print("\nscored invoices", scored)
print(f"overall field accuracy {total_match / total_gold:.1%}")
print(f"invoices with invoice_no, both GSTINs, tax, and total all correct {key_pass / max(scored, 1):.1%}")
print(f"\n{'field':<18} {'accuracy':>8} {'missing':>8} {'wrong':>7}")
rows = []
for key, s in stats.items():
    n = s["gold_present"] or 1
    rows.append((s["match"] / n, key, s))
for _, key, s in sorted(rows):
    n = s["gold_present"] or 1
    print(f"{key:<18} {s['match']/n:8.1%} {s['missing']/n:8.1%} {s['wrong']/n:7.1%}")

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
scored 10
scored 20

scored invoices 22
overall field accuracy 64.2%
invoices with invoice_no, both GSTINs, tax, and total all correct 18.2%

field              accuracy  missing   wrong
vendor_gstin          22.7%    63.6%   13.6%
vendor                31.8%    63.6%    4.5%
customer_gstin        59.1%     4.5%   36.4%
customer              63.6%     4.5%   31.8%
irn                   65.0%     0.0%   35.0%
tax                   65.0%    35.0%    0.0%
line_count            86.4%     9.1%    4.5%
total                 86.4%     4.5%    9.1%
invoice_no            90.5%     4.8%    4.8%
invoice_date          95.5%     4.5%    0.0%

In [ ]:
import gc
import json
from pathlib import Path

import torch
from google.colab import drive
from unsloth import FastLanguageModel

drive.mount("/content/drive")

for name in ("model", "tokenizer"):
    if name in dir():
        del globals()[name]
gc.collect()
torch.cuda.empty_cache()

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora_v2",
    max_seq_length=8192,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

row = None
with Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl").open(encoding="utf-8") as f:
    for line in f:
        cand = json.loads(line)
        if len(cand.get("ocr_text") or "") <= 6000:
            row = cand
            break
if row is None:
    raise SystemExit("no short val invoice")

prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
text = tokenizer.apply_chat_template(
    [{"role": "user", "content": prompt}],
    tokenize=False,
    add_generation_prompt=True,
)
inputs = tokenizer(text, return_tensors="pt").to(model.device)
out = model.generate(
    **inputs,
    max_new_tokens=2048,
    do_sample=False,
    use_cache=True,
)
raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True).strip()

print("blob", row["blob_path"])
print("vendor", row.get("vendor"))
print("\n===== OCR TEXT =====\n")
print(row["ocr_text"])
print("\n===== V2 MODEL =====\n")
print(raw)
print("\n===== GEMINI =====\n")
print(json.dumps(row["gemini_json"], ensure_ascii=False, indent=2))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
blob POD/20260330091052_vekrxjeq/ZYDUS_E-INVOICE_-_GMH_-_MARCH_26/Splitted/Invoices/invoice_B159643.pdf
vendor HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.

===== OCR TEXT =====

Page 1 of 1 INVOICE ORIGINAL BUYER'S COPY
HINDUSTAN PHARMA DISTRIBUTORS PVT LTD. Cu. Code.: 012931 Original CREDIT HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.
ASTER G MADEGOWDA PHARMA
#76/1,2nd & 3rd FLOOR,ARUNA Inv..No. : B159643 #76/1,2nd & 3rd FLOOR,ARUNA
#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,
COMPLEX,ABOVE UNION BANK,
MALAVALLI MADURU ROAD BHARATHDI aNtAe G A R M :EL0L2A/H0A3L/L2I026 11:57:50 J.C.RD , BANGALORE - 560002
J.C.RD , BANGALORE - 560002
MANDYA 571422 Rep. : 06 HOSPITAL - ASTER Cust. Code : 012931 06 HOSPITAL - ASTER
Phone : 42248585 Rep Phone : 9901973286 ASTER G MADEGOWDA PHARMA
DL No.: KA-B31-20B-211806 FSSAI NO.: 11221334001797 Phone 9611478881,9980141585 Due Date : 02/03/2026 #1889,ASTER G MADEGOWDA HOSPITAL
E-MaIl: hdK h1A 9-B 563 @1-2 g1 mB a- i2 l.1 c1 o8 m07 DL. No. :K KA A/ /M MD D1 1/ /2 20 1/ /2 24 42 26 64 41 3 Ord No : 26 MALAVALLI MADURU ROAD BHARATHI NAGAR MELLA
GST : 29AACCD7912K1ZD
GST NO. : 29AAFCH9013A1ZV PAN : Prepared By : YASHODA MANDYA
RACK MFR QTY FREE DESCRIPTION PKG. BATCH NO. EX.DT HSNCODE M.R.P RATE DIS % VALUE GST % OLD MRP Ph :
ZYD 5 .ATORVA 80 TAB 10'S IA00905A 06-27 30049079 433.49 264.22 2.00 1294.68 5.00 0.00
ZYD 1 .DOXOLIN TAB 30S IA01261A 08-27 300490 143.83 104.11 2.00 102.03 5.00 0.00
ZYD 5 .NASOCLEAR NASAL SPRAY 20ML TA1116A 11-28 30049069 66.36 41.00 2.00 200.90 5.00 0.00
ZYD 30 .NUCOXIA MR TAB 10'S IA01382B 08-27 30049069 345.26 221.40 2.00 6509.16 5.00 0.00
202508 CUSTOMER SEAL & SIGNATURE COMPULSORY
8272.21
GST% Prod. Value CGST SGST IGST TOT GST Sale Value : B128887 22-12-25 1936.36 70
0% 0.00 Discount : 165.44 B129028 22-12-25 3547.00 70
5 1% 2% 8106 0. .7 07 0 202 0. .6 07 0 202 0. .6 07 0 00 .. 00 00 405 0. .3 04 0 GST Amount : 405.34 B129019 22-12-25 5589.00 70
18% 0.00 0.00 0.00 0.00 0.00 TCS : 0.00 B129005 22-12-25 4639.00 70
28% 0.00 0.00 0.00 0.00 0.00 B129009 22-12-25 7597.00 70
TOT 8106.77 202.67 202.67 0.00 405.34 Rounded Off : -0.11 T.Bills/Outstanding 57 157580.17
Bill No. Date Amount Days Repl : 0.00 CR/DR : 0.00
Bill No. : B159643
B128887 22-12-25 1936.36 70
B129028 22-12-25 3547.00 70 Tot. Item /Qty: NET AMOUNT : 8512.00 Bill Dt. : 02/03/2026 CREDIT
B129019 22-12-25 5589.00 70 4 / 41
B129005 22-12-25 4639.00 70 Sale Value : 8272.21
B129009 22-12-25 7597.00 70 IRN NO.: 670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c Dis : 165.44
57 157580.17 BANK DETAILS: GST : 405.34
TERMS & CONDITIONS: 1) Goods once sold cannot be taken back or exchanged. 2) When you are returning the breakage / expiry / non moving goods it For HINDUSTAN PHARMA CR/DR : 0 0.. 00 00
should be accompanied by debit note as per the GSTrule 3) In case of delay in making payment over and above 21 days interest @18% shall be charged. DISTRIBUTORS PVT LTD. TCS :
4) IN CASE OF EXCESS CHARGES BY OVERSIGHT KINDLY BRING TO OUR NOTICE FOR REFUND. CHECK BATCH No./ITEMS WHILE ACCEPTING AMOUNT : 8512.00
DELIVERY. We are not responsible for Direct payment without sign slip SUBJECT TO BANGALORE JURISDICTION . E.&OE
Powered By Kluster Techno Solutions Ph:9008308484
RACK |  | MFR | QTY |  | FREE | DESCRIPTION |  |  |  | PKG. |  | BATCH NO. | EX.DT | HSNCOD | E M.R.P | RATE | DIS % | VALUE | GST % | OLD MRP
 |  | ZYD | 5 |  |  | .ATORVA 80 TAB |  |  |  | 10'S |  | IA00905A | 06-27 | 30049079 | 433.49 | 264.22 | 2.00 | 1294.68 | 5.00 | 0.00
 |  | ZYD | 1 |  |  | .DOXOLIN TAB |  |  |  | 30S |  | IA01261A | 08-27 | 300490 | 143.83 | 104.11 | 2.00 | 102.03 | 5.00 | 0.00
 |  | ZYD | 5 |  |  | .NASOCLEAR NASAL SPRAY |  |  |  | 20ML |  | TA1116A | 11-28 | 30049069 | 66.36 | 41.00 | 2.00 | 200.90 | 5.00 | 0.00
 |  | ZYD | 30 |  |  | .NUCOXIA MR TAB |  |  |  | 10'S |  | IA01382B | 08-27 | 30049069 | 345.26 | 221.40 | 2.00 | 6509.16 | 5.00 | 0.00
 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
202508 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
GST | % Prod. Value |  |  | CGST |  |  | SGST | IGST | TOT GST |  |  |  |  |  |  |  |  |  |  |
0% | 0.00 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |
5% | 8106.77 |  |  | 202.67 |  |  | 202.67 | 0.00 | 405.34 |  |  |  |  |  |  |  |  |  |  |
12% | 0.00 |  |  | 0.00 |  |  | 0.00 | 0.00 | 0.00 |  |  |  |  |  |  |  |  |  |  |
18% | 0.00 |  |  | 0.00 |  |  | 0.00 | 0.00 | 0.00 |  |  |  |  |  |  |  |  |  |  |
28% | 0.00 |  |  | 0.00 |  |  | 0.00 | 0.00 | 0.00 |  |  |  |  |  |  |  |  |  |  |
TOT | 8106.77 |  |  | 202.67 202.67 |  |  |  | 0.00 | 405.34 |  |  |  |  |  |  |  |  |  |  |
Bill No. Date Amount Days |  |  |  |  |  |  |  | Repl : 0.00 |  |  |  |  |  |  |  |  |  |  |  |
B128887 22-12-25 1936.36 70
B129028 22-12-25 3547.00 70
B129019 22-12-25 5589.00 70
B129005 22-12-25 4639.00 70
B129009 22-12-25 7597.00 70 |  |  |  |  |  |  |  | Tot. Item /Qty:
4 / 41 |  |  |  |  |  |  |  |  |  |  |  |
57 157580.17 |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |  |

===== V2 MODEL =====

{"invoice_summary": {"irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c", "tax": "405.34", "total": "8512.00", "vendor": "None", "customer": "ASTER G MADEGOWDA PHARMA", "invoice_no": "B159643", "invoice_date": "2025-12-22", "vendor_gstin": "", "customer_gstin": "29AACCD7912K1ZD", "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nMALAVALLI MADURU ROAD BHARATHDI\nJ.C.RD , BANGALORE - 560002"}, "line_items": {"count": 4, "items": [{"hsn_code": "30049079", "quantity": "5", "sku_code": null, "unit_price": "264.22", "total_amount": "1294.68", "lot_batch_number": "IA00905A", "additional_fields": {"mfg": "ZYD", "mrp": "433.49", "expiry_date": "06-27", "free_quantity": "0"}, "product_description": ".ATORVA 80 TAB"}, {"hsn_code": "300490", "quantity": "1", "sku_code": null, "unit_price": "104.11", "total_amount": "102.03", "lot_batch_number": "IA01261A", "additional_fields": {"mfg": "ZYD", "mrp": "143.83", "expiry_date": "08-27", "free_quantity": "0"}, "product_description": ".DOXOLIN TAB"}, {"hsn_code": "30049069", "quantity": "5", "sku_code": null, "unit_price": "41.00", "total_amount": "200.90", "lot_batch_number": "TA1116A", "additional_fields": {"mfg": "ZYD", "mrp": "66.36", "expiry_date": "11-28", "free_quantity": "0"}, "product_description": ".NASOCLEAR NASAL SPRAY"}, {"hsn_code": "30049069", "quantity": "30", "sku_code": null, "unit_price": "221.40", "total_amount": "6509.16", "lot_batch_number": "IA01382B", "additional_fields": {"mfg": "ZYD", "mrp": "345.26", "expiry_date": "08-27", "free_quantity": "0"}, "product_description": ".NUCOXIA MR TAB"}], "title": "line items (with lot / batch)", "has_quantity_info": true, "has_lot_batch_info": true, "items_with_quantity": 4, "items_with_lot_batch": 4, "standardized_columns": {"discount": "discount", "hsn_code": "hsn/sac code", "quantity": "quantity", "sku_code": "sku/item code", "tax_amount": "tax %", "unit_price": "unit price", "total_amount": "total amount", "unit_of_measure": "unit of quantity", "lot_batch_number": "lot/batch number", "additional_fields": "other detected fields", "product_description": "product/item description"}}}

===== GEMINI =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-02-02",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nJ.C.RD , BANGALORE - 560002"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": "ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": "NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

In [ ]:
import json
import random
from pathlib import Path

from datasets import Dataset
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only
from trl import SFTTrainer, SFTConfig

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)
max_seq_length = 8192
SEED = 3407
random.seed(SEED)

# Load v2. Do not overwrite it.
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora_v2",
    max_seq_length=max_seq_length,
    dtype=None,
    load_in_4bit=True,
)
model.train()
trainable = 0
for name, param in model.named_parameters():
    if "lora_" in name:
        param.requires_grad = True
        trainable += param.numel()
print("trainable", trainable)
assert trainable > 0, "adapter did not load as trainable"

# Mix batch 1 (vendor header) + batch 2 (lines / totals) so v2 does not forget.
batch_paths = [
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_001.jsonl"),
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_002.jsonl"),
]

rows = []
for path in batch_paths:
    n = 0
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            row = json.loads(line)
            rows.append({
                "source": path.name,
                "conversations": [
                    {
                        "role": "user",
                        "content": INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip(),
                    },
                    {
                        "role": "assistant",
                        "content": json.dumps(row["gemini_json"], ensure_ascii=False),
                    },
                ],
            })
            n += 1
    print("loaded", path.name, n)

random.shuffle(rows)
print("mixed total", len(rows))

def to_text(batch):
    return {
        "text": [
            tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False)
            for c in batch["conversations"]
        ]
    }

dataset = Dataset.from_list(rows).map(to_text, batched=True)
dataset = dataset.filter(
    lambda ex: len(tokenizer(ex["text"], add_special_tokens=False)["input_ids"]) <= max_seq_length
)
print("kept", len(dataset))
dataset = dataset.remove_columns([c for c in dataset.column_names if c != "text"])

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        packing=False,
        dataset_num_proc=1,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=2e-5,  # much gentler than v2's 1e-4
        warmup_steps=20,
        logging_steps=10,
        save_strategy="steps",
        save_steps=50,
        save_total_limit=3,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=SEED,
        output_dir="/content/drive/MyDrive/invoice_lora_v3_checkpoints",
        report_to="none",
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)
print(trainer.train())
model.save_pretrained("/content/drive/MyDrive/invoice_lora_v3")
tokenizer.save_pretrained("/content/drive/MyDrive/invoice_lora_v3")
print("saved /content/drive/MyDrive/invoice_lora_v3")

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
trainable 18464768
loaded pdfplumber_train_batch_001.jsonl 5000
loaded pdfplumber_train_batch_002.jsonl 5000
mixed total 10000

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/10000 [00:00<?, ? examples/s]

kept 9169

Unsloth: Tokenizing ["text"]:   0%|          | 0/9169 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

Map (num_proc=6):   0%|          | 0/9169 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 9,169 | Num Epochs = 1 | Total steps = 1,147
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

In [ ]:
from pathlib import Path
from google.colab import drive
drive.mount("/content/drive")

ckpt = Path("/content/drive/MyDrive/invoice_lora_v3_checkpoints")
final = Path("/content/drive/MyDrive/invoice_lora_v3")
print("v3 final exists:", final.exists())
print("ckpt dir exists:", ckpt.exists())
if ckpt.exists():
    print("ckpt folders:", sorted([p.name for p in ckpt.iterdir() if p.is_dir()]))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
v3 final exists: False
ckpt dir exists: True
ckpt folders: ['checkpoint-1000', 'checkpoint-1050', 'checkpoint-950']

In [ ]:
import json
import random
from pathlib import Path

from datasets import Dataset
from transformers.trainer_utils import get_last_checkpoint
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only
from trl import SFTTrainer, SFTConfig

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)
max_seq_length = 8192
SEED = 3407
random.seed(SEED)

ckpt_dir = "/content/drive/MyDrive/invoice_lora_v3_checkpoints"
last_ckpt = get_last_checkpoint(ckpt_dir)
print("resuming from", last_ckpt)
assert last_ckpt is not None, "no checkpoint found — rerun original v3 cell"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora_v2",
    max_seq_length=max_seq_length,
    dtype=None,
    load_in_4bit=True,
)
model.train()
trainable = 0
for name, param in model.named_parameters():
    if "lora_" in name:
        param.requires_grad = True
        trainable += param.numel()
print("trainable", trainable)
assert trainable > 0

batch_paths = [
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_001.jsonl"),
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_002.jsonl"),
]
rows = []
for path in batch_paths:
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            row = json.loads(line)
            rows.append({
                "conversations": [
                    {"role": "user", "content": INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()},
                    {"role": "assistant", "content": json.dumps(row["gemini_json"], ensure_ascii=False)},
                ]
            })
random.shuffle(rows)

def to_text(batch):
    return {"text": [
        tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False)
        for c in batch["conversations"]
    ]}

dataset = Dataset.from_list(rows).map(to_text, batched=True)
dataset = dataset.filter(
    lambda ex: len(tokenizer(ex["text"], add_special_tokens=False)["input_ids"]) <= max_seq_length
)
dataset = dataset.remove_columns([c for c in dataset.column_names if c != "text"])
print("kept", len(dataset))

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        packing=False,
        dataset_num_proc=1,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=2e-5,
        warmup_steps=20,
        logging_steps=10,
        save_strategy="steps",
        save_steps=50,
        save_total_limit=3,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=SEED,
        output_dir=ckpt_dir,
        report_to="none",
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)
print(trainer.train(resume_from_checkpoint=last_ckpt))
model.save_pretrained("/content/drive/MyDrive/invoice_lora_v3")
tokenizer.save_pretrained("/content/drive/MyDrive/invoice_lora_v3")
print("saved /content/drive/MyDrive/invoice_lora_v3")

resuming from /content/drive/MyDrive/invoice_lora_v3_checkpoints/checkpoint-1050
==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
trainable 18464768

Map:   0%|          | 0/10000 [00:00<?, ? examples/s]

Filter:   0%|          | 0/10000 [00:00<?, ? examples/s]

kept 9169

Unsloth: Tokenizing ["text"]:   0%|          | 0/9169 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

Map (num_proc=6):   0%|          | 0/9169 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 9,169 | Num Epochs = 1 | Total steps = 1,147
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

TrainOutput(global_step=1146, training_loss=0.0010049580084403771, metrics={'train_runtime': 384.109, 'train_samples_per_second': 23.871, 'train_steps_per_second': 2.986, 'total_flos': 2.973430875661855e+17, 'train_loss': 0.0010049580084403771, 'epoch': 0.9998909368524376})
saved /content/drive/MyDrive/invoice_lora_v3

In [ ]:
import json, random, re
from pathlib import Path
from collections import defaultdict

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora_v3",
    max_seq_length=8192,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)

FIELDS = [
    "invoice_no", "invoice_date", "vendor", "customer",
    "vendor_gstin", "customer_gstin", "tax", "total", "irn",
]

def get_summary(obj):
    if not isinstance(obj, dict):
        return {}
    return obj.get("invoice_summary") or {}

def line_count(obj):
    if not isinstance(obj, dict):
        return None
    li = obj.get("line_items")
    if isinstance(li, dict) and isinstance(li.get("items"), list):
        return len(li["items"])
    if isinstance(li, list):
        return len(li)
    return None

def norm(v):
    if v is None:
        return ""
    return re.sub(r"\s+", " ", str(v).strip().upper())

def parse_model(text):
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None

# Same sample style: 2 invoices per held-out vendor, skip long prompts
by_vendor = defaultdict(list)
with Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl").open(encoding="utf-8") as f:
    for line in f:
        row = json.loads(line)
        by_vendor[row.get("vendor") or "UNKNOWN"].append(row)

random.seed(3407)
sample = []
for vendor, rows in sorted(by_vendor.items(), key=lambda x: -len(x[1])):
    if len(sample) >= 24:
        break
    random.shuffle(rows)
    for row in rows[:2]:
        sample.append(row)

stats = {k: {"ok": 0, "missing": 0, "wrong": 0, "n": 0} for k in FIELDS + ["line_count"]}
strict_ok = 0
scored = 0

for i, row in enumerate(sample, 1):
    prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    if len(tokenizer(text, add_special_tokens=False)["input_ids"]) > 6000:
        continue
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=2048, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    pred = parse_model(raw)
    gold = row["gemini_json"]
    gs, ps = get_summary(gold), get_summary(pred) if pred else {}

    for field in FIELDS:
        g, p = norm(gs.get(field)), norm(ps.get(field)) if pred else ""
        stats[field]["n"] += 1
        if not p:
            stats[field]["missing"] += 1
        elif p == g:
            stats[field]["ok"] += 1
        else:
            stats[field]["wrong"] += 1

    gc, pc = line_count(gold), line_count(pred) if pred else None
    stats["line_count"]["n"] += 1
    if pc is None:
        stats["line_count"]["missing"] += 1
    elif pc == gc:
        stats["line_count"]["ok"] += 1
    else:
        stats["line_count"]["wrong"] += 1

    need = ["invoice_no", "vendor_gstin", "customer_gstin", "tax", "total"]
    if pred and all(norm(ps.get(k)) == norm(gs.get(k)) and norm(ps.get(k)) for k in need):
        strict_ok += 1
    scored += 1
    if scored % 10 == 0:
        print("scored", scored)

total_ok = sum(stats[k]["ok"] for k in stats)
total_n = sum(stats[k]["n"] for k in stats)
print("\nscored invoices", scored)
print(f"overall field accuracy {100 * total_ok / max(total_n, 1):.1f}%")
print(f"invoices with invoice_no, both GSTINs, tax, and total all correct {100 * strict_ok / max(scored, 1):.1f}%")
print(f"\n{'field':18} {'accuracy':>8} {'missing':>8} {'wrong':>8}")
for field in sorted(stats, key=lambda k: stats[k]["ok"] / max(stats[k]["n"], 1)):
    s = stats[field]
    n = max(s["n"], 1)
    print(f"{field:18} {100*s['ok']/n:7.1f}% {100*s['missing']/n:7.1f}% {100*s['wrong']/n:7.1f}%")

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
scored 10
scored 20

scored invoices 21
overall field accuracy 70.5%
invoices with invoice_no, both GSTINs, tax, and total all correct 9.5%

field              accuracy  missing    wrong
customer_gstin        33.3%     9.5%    57.1%
vendor_gstin          52.4%    33.3%    14.3%
irn                   52.4%     4.8%    42.9%
vendor                66.7%     4.8%    28.6%
customer              76.2%     4.8%    19.0%
tax                   76.2%    23.8%     0.0%
total                 76.2%     4.8%    19.0%
invoice_no            81.0%     4.8%    14.3%
invoice_date          95.2%     4.8%     0.0%
line_count            95.2%     4.8%     0.0%

In [ ]:
import gc
import json
import re
from copy import deepcopy
from pathlib import Path

import torch
from unsloth import FastLanguageModel

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)

# Header fields: trust v3, but if blank use v1
FALLBACK_FIELDS = ["vendor", "vendor_gstin", "tax", "irn"]

def parse_json(text):
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None

def is_blank(v):
    if v is None:
        return True
    if isinstance(v, str) and not v.strip():
        return True
    return False

def add_pan_from_gstin(summary):
    summary = dict(summary or {})
    for src, dst in (("vendor_gstin", "vendor_pan"), ("customer_gstin", "customer_pan")):
        g = re.sub(r"[^A-Z0-9]", "", str(summary.get(src) or "").upper())
        if len(g) == 15:
            summary[dst] = g[2:12]
        else:
            summary.setdefault(dst, None)
    return summary

def stitch(v3_obj, v1_obj):
    if not isinstance(v3_obj, dict):
        v3_obj = {}
    if not isinstance(v1_obj, dict):
        v1_obj = {}
    out = deepcopy(v3_obj) if v3_obj else {"invoice_summary": {}, "line_items": v1_obj.get("line_items")}
    s3 = out.setdefault("invoice_summary", {})
    s1 = (v1_obj.get("invoice_summary") or {}) if isinstance(v1_obj, dict) else {}
    used = []
    for field in FALLBACK_FIELDS:
        if is_blank(s3.get(field)) and not is_blank(s1.get(field)):
            s3[field] = s1[field]
            used.append(field)
    s3 = add_pan_from_gstin(s3)
    out["invoice_summary"] = s3
    if not out.get("line_items") and v1_obj.get("line_items"):
        out["line_items"] = v1_obj["line_items"]
        used.append("line_items")
    return out, used

def generate(model, tokenizer, ocr_text):
    prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr_text.strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=2048, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    return raw, parse_json(raw)

# Load base once, attach both adapters
for name in ("model", "tokenizer"):
    if name in globals():
        del globals()[name]
gc.collect()
torch.cuda.empty_cache()

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=8192,
    dtype=None,
    load_in_4bit=True,
)
model.load_adapter("/content/drive/MyDrive/invoice_lora_v3", adapter_name="v3")
model.load_adapter("/content/drive/MyDrive/invoice_lora", adapter_name="v1")
FastLanguageModel.for_inference(model)

# One short held-out invoice
row = None
with Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl").open(encoding="utf-8") as f:
    for line in f:
        cand = json.loads(line)
        if len(cand.get("ocr_text") or "") <= 6000:
            row = cand
            break
assert row is not None

model.set_adapter("v3")
raw_v3, obj_v3 = generate(model, tokenizer, row["ocr_text"])

model.set_adapter("v1")
raw_v1, obj_v1 = generate(model, tokenizer, row["ocr_text"])

hybrid, used = stitch(obj_v3, obj_v1)

print("blob", row["blob_path"])
print("fallback fields used from v1:", used or "(none)")
print("\n===== V3 =====\n")
print(json.dumps(obj_v3, ensure_ascii=False, indent=2) if obj_v3 else raw_v3)
print("\n===== V1 =====\n")
print(json.dumps(obj_v1, ensure_ascii=False, indent=2) if obj_v1 else raw_v1)
print("\n===== HYBRID =====\n")
print(json.dumps(hybrid, ensure_ascii=False, indent=2))
print("\n===== GEMINI =====\n")
print(json.dumps(row["gemini_json"], ensure_ascii=False, indent=2))

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.13/dist-packages/peft/tuners/tuners_utils.py:305: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

blob POD/20260330091052_vekrxjeq/ZYDUS_E-INVOICE_-_GMH_-_MARCH_26/Splitted/Invoices/invoice_B159643.pdf
fallback fields used from v1: ['vendor_gstin']

===== V3 =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "None",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-03-02",
    "vendor_gstin": "",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nMALAVALLI MADURU ROAD BHARATHDI aNatA G A R M :EL0L2A/H0A3L/L2I026 11:57:50 J.C.RD , BANGALORE - 560002"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": ".ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": ".NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of quantity",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

===== V1 =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2025-12-22",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AAFCH9013A1ZV",
    "customer_address": "#76/1,2nd & 3rd FLOOR,ARUNA\n#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nMALAVALLI MADURU ROAD BHARATHDI aNtA"
  },
  "line_items": {
    "count": 5,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": ".ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": ".NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".NUCOXIA MR TAB"
      },
      {
        "hsn_code": "",
        "quantity": "5",
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "",
        "recovered_from_ocr": true,
        "product_description": "IA00905A"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 5,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

===== HYBRID =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "None",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-03-02",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nMALAVALLI MADURU ROAD BHARATHDI aNatA G A R M :EL0L2A/H0A3L/L2I026 11:57:50 J.C.RD , BANGALORE - 560002",
    "vendor_pan": "AACCD7912K",
    "customer_pan": "AACCD7912K"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": ".ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": ".NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of quantity",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

===== GEMINI =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-02-02",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nJ.C.RD , BANGALORE - 560002"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": "ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": "NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

In [ ]:
import json
import random
import re
from pathlib import Path

from datasets import Dataset
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only
from trl import SFTTrainer, SFTConfig

SEED = 3407
random.seed(SEED)
max_seq_length = 8192

GSTIN_RE = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")
REPAIR_KEYS = ("vendor", "vendor_gstin", "tax", "irn")

INSTRUCTION = (
    "From the invoice OCR text, extract ONLY these fields. "
    "Reply with JSON only, with key invoice_summary containing exactly: "
    "vendor, vendor_gstin, tax, irn. "
    "Use null if a field is not present. Do not invent GSTINs. "
    "vendor_gstin must be a 15-character GSTIN when present."
)

def norm_gstin(v):
    return re.sub(r"[^A-Z0-9]", "", str(v or "").upper())

def is_bad_name(v):
    if v is None:
        return True
    t = str(v).strip()
    return (not t) or t.lower() in {"none", "null", "nan", "n/a", "-"}

def repair_label(summary):
    summary = summary or {}
    gstin = norm_gstin(summary.get("vendor_gstin"))
    if not GSTIN_RE.fullmatch(gstin):
        return None
    vendor = summary.get("vendor")
    if is_bad_name(vendor):
        return None
    out = {
        "vendor": str(vendor).strip(),
        "vendor_gstin": gstin,
        "tax": summary.get("tax") if summary.get("tax") not in ("",) else None,
        "irn": summary.get("irn") if summary.get("irn") not in ("",) else None,
    }
    # Keep only the 4 keys, exact schema every row
    return {"invoice_summary": {k: out.get(k) for k in REPAIR_KEYS}}

# Fresh specialist — do NOT load v3
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=max_seq_length,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    lora_alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=SEED,
)

batch_paths = [
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_001.jsonl"),
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_train_batch_002.jsonl"),
]

rows = []
skipped = 0
for path in batch_paths:
    n_keep = 0
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            row = json.loads(line)
            label = repair_label((row.get("gemini_json") or {}).get("invoice_summary"))
            ocr = (row.get("ocr_text") or "").strip()
            if not label or not ocr:
                skipped += 1
                continue
            rows.append({
                "conversations": [
                    {"role": "user", "content": INSTRUCTION + "\n\nOCR text:\n" + ocr},
                    {"role": "assistant", "content": json.dumps(label, ensure_ascii=False)},
                ]
            })
            n_keep += 1
    print("kept from", path.name, n_keep)

random.shuffle(rows)
print("train rows", len(rows), "skipped", skipped)
assert len(rows) > 1000, "too few clean repair labels"

def to_text(batch):
    return {
        "text": [
            tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False)
            for c in batch["conversations"]
        ]
    }

dataset = Dataset.from_list(rows).map(to_text, batched=True)
dataset = dataset.filter(
    lambda ex: len(tokenizer(ex["text"], add_special_tokens=False)["input_ids"]) <= max_seq_length
)
print("kept after length filter", len(dataset))
dataset = dataset.remove_columns([c for c in dataset.column_names if c != "text"])

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
        dataset_text_field="text",
        max_seq_length=max_seq_length,
        packing=False,
        dataset_num_proc=1,
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        num_train_epochs=1,
        learning_rate=2e-5,
        warmup_steps=20,
        logging_steps=10,
        save_strategy="steps",
        save_steps=50,
        save_total_limit=3,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=SEED,
        output_dir="/content/drive/MyDrive/invoice_lora_repair_checkpoints",
        report_to="none",
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)
print(trainer.train())
model.save_pretrained("/content/drive/MyDrive/invoice_lora_repair")
tokenizer.save_pretrained("/content/drive/MyDrive/invoice_lora_repair")
print("saved /content/drive/MyDrive/invoice_lora_repair")

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
kept from pdfplumber_train_batch_001.jsonl 4969
kept from pdfplumber_train_batch_002.jsonl 4231
train rows 9200 skipped 800

Map:   0%|          | 0/9200 [00:00<?, ? examples/s]

Filter:   0%|          | 0/9200 [00:00<?, ? examples/s]

kept after length filter 8866

Unsloth: Tokenizing ["text"]:   0%|          | 0/8866 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

Map (num_proc=6):   0%|          | 0/8866 [00:00<?, ? examples/s]

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 8,866 | Num Epochs = 1 | Total steps = 1,109
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 8
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 8 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

TrainOutput(global_step=1109, training_loss=0.04189399387301143, metrics={'train_runtime': 4106.8142, 'train_samples_per_second': 2.159, 'train_steps_per_second': 0.27, 'total_flos': 2.550328374315479e+17, 'train_loss': 0.04189399387301143, 'epoch': 1.0})
saved /content/drive/MyDrive/invoice_lora_repair

In [ ]:
import json, random, re
from pathlib import Path
from collections import defaultdict

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/drive/MyDrive/invoice_lora_repair",
    max_seq_length=8192,
    dtype=None,
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)

INSTRUCTION = (
    "From the invoice OCR text, extract ONLY these fields. "
    "Reply with JSON only, with key invoice_summary containing exactly: "
    "vendor, vendor_gstin, tax, irn. "
    "Use null if a field is not present. Do not invent GSTINs. "
    "vendor_gstin must be a 15-character GSTIN when present."
)
FIELDS = ["vendor", "vendor_gstin", "tax", "irn"]

def norm(v):
    if v is None:
        return ""
    return re.sub(r"\s+", " ", str(v).strip().upper())

def parse_model(text):
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None

by_vendor = defaultdict(list)
with Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl").open(encoding="utf-8") as f:
    for line in f:
        row = json.loads(line)
        by_vendor[row.get("vendor") or "UNKNOWN"].append(row)

random.seed(3407)
sample = []
for vendor, rows in sorted(by_vendor.items(), key=lambda x: -len(x[1])):
    if len(sample) >= 24:
        break
    random.shuffle(rows)
    sample.extend(rows[:2])

stats = {k: {"ok": 0, "missing": 0, "wrong": 0, "n": 0} for k in FIELDS}
scored = 0
for row in sample:
    prompt = INSTRUCTION + "\n\nOCR text:\n" + row["ocr_text"].strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    if len(tokenizer(text, add_special_tokens=False)["input_ids"]) > 6000:
        continue
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=256, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    pred = parse_model(raw)
    ps = (pred or {}).get("invoice_summary") or {}
    gs = (row["gemini_json"] or {}).get("invoice_summary") or {}
    for field in FIELDS:
        g, p = norm(gs.get(field)), norm(ps.get(field))
        stats[field]["n"] += 1
        if not p or p in {"NONE", "NULL"}:
            stats[field]["missing"] += 1
        elif p == g:
            stats[field]["ok"] += 1
        else:
            stats[field]["wrong"] += 1
    scored += 1
    if scored % 10 == 0:
        print("scored", scored)

print("\nscored", scored)
print(f"{'field':16} {'accuracy':>8} {'missing':>8} {'wrong':>8}")
for field in FIELDS:
    s = stats[field]
    n = max(s["n"], 1)
    print(f"{field:16} {100*s['ok']/n:7.1f}% {100*s['missing']/n:7.1f}% {100*s['wrong']/n:7.1f}%")

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
scored 10
scored 20

scored 21
field            accuracy  missing    wrong
vendor              76.2%     9.5%    14.3%
vendor_gstin        71.4%     9.5%    19.0%
tax                 57.1%    23.8%    19.0%
irn                 61.9%     9.5%    28.6%

In [ ]:
import gc
import json
import re
from copy import deepcopy
from pathlib import Path

import torch
from unsloth import FastLanguageModel

# ---------- config ----------
V3_PATH = "/content/drive/MyDrive/invoice_lora_v3"
V1_PATH = "/content/drive/MyDrive/invoice_lora"
VAL_PATH = "/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl"
MAX_SEQ = 8192

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)

HEADER_FIELDS = ["vendor", "vendor_gstin", "tax", "irn"]
GSTIN_RE = re.compile(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]")
IRN_RE = re.compile(r"\b[a-fA-F0-9]{64}\b")

# ---------- helpers ----------
def is_blank(v):
    if v is None:
        return True
    if isinstance(v, str):
        t = v.strip()
        if not t:
            return True
        if t.lower() in {"none", "null", "nan", "n/a", "-"}:
            return True
    return False

def norm_gstin(v):
    return re.sub(r"[^A-Z0-9]", "", str(v or "").upper())

def valid_gstin(v):
    g = norm_gstin(v)
    return bool(GSTIN_RE.fullmatch(g)), g

def parse_json(text):
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None

def generate(model, tokenizer, ocr_text, max_new_tokens=2048):
    prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr_text.strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    return raw, parse_json(raw)

def regex_fill(summary, ocr_text, used):
    summary = dict(summary or {})
    ocr = ocr_text or ""
    compact = re.sub(r"\s+", "", ocr.upper())

    # GSTINs in OCR order
    found = []
    for m in GSTIN_RE.finditer(re.sub(r"[^A-Z0-9]", "", ocr.upper())):
        g = m.group()
        if g not in found:
            found.append(g)

    ok, cur = valid_gstin(summary.get("vendor_gstin"))
    if (not ok) and found:
        summary["vendor_gstin"] = found[0]
        used.append("regex:vendor_gstin")

    ok_c, _ = valid_gstin(summary.get("customer_gstin"))
    if (not ok_c) and len(found) >= 2:
        # second distinct GSTIN often buyer; only fill if blank/invalid
        summary["customer_gstin"] = found[1]
        used.append("regex:customer_gstin")
    elif (not ok_c) and len(found) == 1 and found[0] != norm_gstin(summary.get("vendor_gstin")):
        summary["customer_gstin"] = found[0]
        used.append("regex:customer_gstin")

    if is_blank(summary.get("irn")):
        m = IRN_RE.search(ocr)
        if m:
            summary["irn"] = m.group().lower()
            used.append("regex:irn")

    return summary

def needs_header_fallback(summary):
    summary = summary or {}
    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(summary.get(k))
            if not ok:
                return True
        elif is_blank(summary.get(k)):
            return True
    return False

def merge_header_from_v1(base_obj, v1_obj, used):
    out = deepcopy(base_obj) if isinstance(base_obj, dict) else {"invoice_summary": {}, "line_items": None}
    s = out.setdefault("invoice_summary", {})
    s1 = ((v1_obj or {}).get("invoice_summary") or {}) if isinstance(v1_obj, dict) else {}

    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(s.get(k))
            ok1, g1 = valid_gstin(s1.get(k))
            if (not ok) and ok1:
                s[k] = g1
                used.append(f"v1:{k}")
        else:
            if is_blank(s.get(k)) and not is_blank(s1.get(k)):
                s[k] = s1[k]
                used.append(f"v1:{k}")

    out["invoice_summary"] = s
    # never take v1 line_items
    return out

def run_pipeline(model, tokenizer, ocr_text):
    used = []

    model.set_adapter("v3")
    raw_v3, obj_v3 = generate(model, tokenizer, ocr_text)
    if not isinstance(obj_v3, dict):
        obj_v3 = {"invoice_summary": {}, "line_items": None, "_raw": raw_v3}

    summary = dict(obj_v3.get("invoice_summary") or {})
    summary = regex_fill(summary, ocr_text, used)
    obj_v3["invoice_summary"] = summary

    obj_v1 = None
    raw_v1 = None
    if needs_header_fallback(summary):
        model.set_adapter("v1")
        raw_v1, obj_v1 = generate(model, tokenizer, ocr_text)
        obj_v3 = merge_header_from_v1(obj_v3, obj_v1, used)

    return {
        "final": obj_v3,
        "v3_raw": raw_v3,
        "v1_raw": raw_v1,
        "v1_obj": obj_v1,
        "fallback_used": used,
    }

# ---------- load once ----------
for name in ("model", "tokenizer"):
    if name in globals():
        del globals()[name]
gc.collect()
torch.cuda.empty_cache()

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=MAX_SEQ,
    dtype=None,
    load_in_4bit=True,
)
model.load_adapter(V3_PATH, adapter_name="v3")
model.load_adapter(V1_PATH, adapter_name="v1")
FastLanguageModel.for_inference(model)
print("loaded v3 + v1 adapters")

# ---------- one short val invoice demo ----------
row = None
with Path(VAL_PATH).open(encoding="utf-8") as f:
    for line in f:
        cand = json.loads(line)
        if len(cand.get("ocr_text") or "") <= 6000:
            row = cand
            break
assert row is not None, "no short val row"

result = run_pipeline(model, tokenizer, row["ocr_text"])

print("blob", row["blob_path"])
print("fallback_used", result["fallback_used"] or "(none)")
print("\n===== FINAL (v3 + regex + v1 header) =====\n")
print(json.dumps(result["final"], ensure_ascii=False, indent=2))
print("\n===== GEMINI =====\n")
print(json.dumps(row["gemini_json"], ensure_ascii=False, indent=2))

==((====))==  Unsloth 2026.9.4: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-40GB. Num GPUs = 1. Max memory: 39.494 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.13/dist-packages/peft/tuners/tuners_utils.py:305: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

loaded v3 + v1 adapters
blob POD/20260330091052_vekrxjeq/ZYDUS_E-INVOICE_-_GMH_-_MARCH_26/Splitted/Invoices/invoice_B159643.pdf
fallback_used ['regex:vendor_gstin', 'v1:vendor']

===== FINAL (v3 + regex + v1 header) =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-03-02",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nMALAVALLI MADURU ROAD BHARATHDI aNatA G A R M :EL0L2A/H0A3L/L2I026 11:57:50 J.C.RD , BANGALORE - 560002"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": ".ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": ".NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": ".NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of quantity",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

===== GEMINI =====

{
  "invoice_summary": {
    "irn": "670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c",
    "tax": "405.34",
    "total": "8512.00",
    "vendor": "HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.",
    "customer": "ASTER G MADEGOWDA PHARMA",
    "invoice_no": "B159643",
    "invoice_date": "2026-02-02",
    "vendor_gstin": "29AACCD7912K1ZD",
    "customer_gstin": "29AACCD7912K1ZD",
    "customer_address": "#1889,ASTER G MADEGOWDA HOSPITAL COMPLEX,ABOVE UNION BANK,\nJ.C.RD , BANGALORE - 560002"
  },
  "line_items": {
    "count": 4,
    "items": [
      {
        "hsn_code": "30049079",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "264.22",
        "total_amount": "1294.68",
        "lot_batch_number": "IA00905A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "433.49",
          "expiry_date": "06-27",
          "free_quantity": "0"
        },
        "product_description": "ATORVA 80 TAB"
      },
      {
        "hsn_code": "300490",
        "quantity": "1",
        "sku_code": null,
        "unit_price": "104.11",
        "total_amount": "102.03",
        "lot_batch_number": "IA01261A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "143.83",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "DOXOLIN TAB"
      },
      {
        "hsn_code": "30049069",
        "quantity": "5",
        "sku_code": null,
        "unit_price": "41.00",
        "total_amount": "200.90",
        "lot_batch_number": "TA1116A",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "66.36",
          "expiry_date": "11-28",
          "free_quantity": "0"
        },
        "product_description": "NASOCLEAR NASAL SPRAY"
      },
      {
        "hsn_code": "30049069",
        "quantity": "30",
        "sku_code": null,
        "unit_price": "221.40",
        "total_amount": "6509.16",
        "lot_batch_number": "IA01382B",
        "additional_fields": {
          "mfg": "ZYD",
          "mrp": "345.26",
          "expiry_date": "08-27",
          "free_quantity": "0"
        },
        "product_description": "NUCOXIA MR TAB"
      }
    ],
    "title": "line items (with lot / batch)",
    "has_quantity_info": true,
    "has_lot_batch_info": true,
    "items_with_quantity": 4,
    "items_with_lot_batch": 4,
    "standardized_columns": {
      "discount": "discount",
      "hsn_code": "hsn/sac code",
      "quantity": "quantity",
      "sku_code": "sku/item code",
      "tax_amount": "tax %",
      "unit_price": "unit price",
      "total_amount": "total amount",
      "unit_of_measure": "unit of measure",
      "lot_batch_number": "lot/batch number",
      "additional_fields": "other detected fields",
      "product_description": "product/item description"
    }
  }
}

In [ ]:
import shutil
from pathlib import Path
from google.colab import files, drive

drive.mount("/content/drive")

root = Path("/content/drive/MyDrive")
out_dir = Path("/content/model_export")
out_dir.mkdir(exist_ok=True)

folders = [
    "invoice_lora",          # v1
    "invoice_lora_v2",       # v2
    "invoice_lora_v3",       # v3
    "invoice_lora_repair",   # repair
]

for name in folders:
    src = root / name
    if not src.exists():
        print("MISSING", src)
        continue
    dest = out_dir / name
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)
    print("copied", name, "->", dest)

zip_path = Path("/content/invoice_adapters_all")
shutil.make_archive(str(zip_path), "zip", root_dir=out_dir)
print("zip", zip_path.with_suffix(".zip"), "size_mb", zip_path.with_suffix(".zip").stat().st_size / 1e6)

files.download(str(zip_path.with_suffix(".zip")))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
copied invoice_lora -> /content/model_export/invoice_lora
copied invoice_lora_v2 -> /content/model_export/invoice_lora_v2
copied invoice_lora_v3 -> /content/model_export/invoice_lora_v3
copied invoice_lora_repair -> /content/model_export/invoice_lora_repair
zip /content/invoice_adapters_all.zip size_mb 289.029322

In [ ]:
"""
Pre-production validation for the invoice cascade:
  v3 (full JSON) -> regex (GSTIN/IRN) -> v1 (header fill-if-blank)

Run in Colab with Drive mounted and a GPU.
Does not train. Does not write Azure. Does not touch SAP.
"""

from __future__ import annotations

import gc
import json
import random
import re
from collections import defaultdict
from copy import deepcopy
from pathlib import Path

import torch
from unsloth import FastLanguageModel

# ---------- paths (Colab Drive) ----------
V3_PATH = "/content/drive/MyDrive/invoice_lora_v3"
V1_PATH = "/content/drive/MyDrive/invoice_lora"
VAL_PATH = "/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl"
OUT_PATH = "/content/drive/MyDrive/pipeline_validation_report.json"

MAX_SEQ = 8192
# Skip invoices whose prompt is too long for this version
MAX_PROMPT_TOKENS = 6000
# How many invoices per held-out vendor (same style as earlier scores)
PER_VENDOR = 2
MAX_VENDORS = 12
SEED = 3407

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)
HEADER_FIELDS = ["vendor", "vendor_gstin", "tax", "irn"]
SCORE_FIELDS = [
    "invoice_no",
    "invoice_date",
    "vendor",
    "customer",
    "vendor_gstin",
    "customer_gstin",
    "tax",
    "total",
    "irn",
]
STRICT_FIELDS = ["invoice_no", "vendor_gstin", "customer_gstin", "tax", "total"]

GSTIN_RE = re.compile(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]")
IRN_RE = re.compile(r"\b[a-fA-F0-9]{64}\b")
SUMMARY_REQUIRED = {
    "invoice_no",
    "invoice_date",
    "vendor",
    "customer",
    "vendor_gstin",
    "customer_gstin",
    "customer_address",
    "irn",
    "tax",
    "total",
}


def is_blank(v) -> bool:
    if v is None:
        return True
    if isinstance(v, str):
        t = v.strip()
        if not t:
            return True
        if t.lower() in {"none", "null", "nan", "n/a", "-"}:
            return True
    return False


def norm(v) -> str:
    if v is None:
        return ""
    return re.sub(r"\s+", " ", str(v).strip().upper())


def norm_gstin(v) -> str:
    return re.sub(r"[^A-Z0-9]", "", str(v or "").upper())


def valid_gstin(v) -> tuple[bool, str]:
    g = norm_gstin(v)
    return bool(re.fullmatch(GSTIN_RE.pattern, g)), g


def parse_json(text):
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None


def line_count(obj):
    if not isinstance(obj, dict):
        return None
    li = obj.get("line_items")
    if isinstance(li, dict) and isinstance(li.get("items"), list):
        return len(li["items"])
    if isinstance(li, list):
        return len(li)
    return None


def schema_ok(obj) -> tuple[bool, list[str]]:
    problems = []
    if not isinstance(obj, dict):
        return False, ["not_a_dict"]
    if "invoice_summary" not in obj:
        problems.append("missing_invoice_summary")
    if "line_items" not in obj:
        problems.append("missing_line_items")
    summary = obj.get("invoice_summary")
    if not isinstance(summary, dict):
        problems.append("invoice_summary_not_dict")
    else:
        missing = SUMMARY_REQUIRED - set(summary.keys())
        if missing:
            problems.append("summary_missing_keys:" + ",".join(sorted(missing)))
    li = obj.get("line_items")
    if isinstance(li, dict):
        if not isinstance(li.get("items"), list):
            problems.append("line_items.items_not_list")
    elif not isinstance(li, list):
        problems.append("line_items_bad_type")
    return len(problems) == 0, problems


def generate(model, tokenizer, ocr_text, max_new_tokens=2048):
    prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr_text.strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=True,
    )
    raw = tokenizer.decode(
        out[0][inputs["input_ids"].shape[-1] :],
        skip_special_tokens=True,
    )
    return raw, parse_json(raw)


def regex_fill(summary, ocr_text, used):
    summary = dict(summary or {})
    ocr = ocr_text or ""
    found = []
    for m in GSTIN_RE.finditer(re.sub(r"[^A-Z0-9]", "", ocr.upper())):
        g = m.group()
        if g not in found:
            found.append(g)

    ok, _ = valid_gstin(summary.get("vendor_gstin"))
    if (not ok) and found:
        summary["vendor_gstin"] = found[0]
        used.append("regex:vendor_gstin")

    ok_c, _ = valid_gstin(summary.get("customer_gstin"))
    if (not ok_c) and len(found) >= 2:
        summary["customer_gstin"] = found[1]
        used.append("regex:customer_gstin")

    if is_blank(summary.get("irn")):
        m = IRN_RE.search(ocr)
        if m:
            summary["irn"] = m.group().lower()
            used.append("regex:irn")

    return summary


def needs_header_fallback(summary) -> bool:
    summary = summary or {}
    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(summary.get(k))
            if not ok:
                return True
        elif is_blank(summary.get(k)):
            return True
    return False


def merge_header_from_v1(base_obj, v1_obj, used):
    out = (
        deepcopy(base_obj)
        if isinstance(base_obj, dict)
        else {"invoice_summary": {}, "line_items": None}
    )
    s = out.setdefault("invoice_summary", {})
    s1 = ((v1_obj or {}).get("invoice_summary") or {}) if isinstance(v1_obj, dict) else {}

    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(s.get(k))
            ok1, g1 = valid_gstin(s1.get(k))
            if (not ok) and ok1:
                s[k] = g1
                used.append(f"v1:{k}")
        else:
            if is_blank(s.get(k)) and not is_blank(s1.get(k)):
                s[k] = s1[k]
                used.append(f"v1:{k}")

    out["invoice_summary"] = s
    return out


def run_pipeline(model, tokenizer, ocr_text):
    used = []
    model.set_adapter("v3")
    raw_v3, obj_v3 = generate(model, tokenizer, ocr_text)
    if not isinstance(obj_v3, dict):
        obj_v3 = {"invoice_summary": {}, "line_items": None}

    summary = dict(obj_v3.get("invoice_summary") or {})
    summary = regex_fill(summary, ocr_text, used)
    obj_v3["invoice_summary"] = summary

    if needs_header_fallback(summary):
        model.set_adapter("v1")
        _, obj_v1 = generate(model, tokenizer, ocr_text)
        obj_v3 = merge_header_from_v1(obj_v3, obj_v1, used)

    return obj_v3, used, raw_v3


def build_sample(val_path: Path):
    by_vendor = defaultdict(list)
    with val_path.open(encoding="utf-8") as f:
        for line in f:
            row = json.loads(line)
            by_vendor[row.get("vendor") or "UNKNOWN"].append(row)

    random.seed(SEED)
    sample = []
    for _, rows in sorted(by_vendor.items(), key=lambda x: -len(x[1])):
        if len(sample) >= MAX_VENDORS * PER_VENDOR:
            break
        random.shuffle(rows)
        sample.extend(rows[:PER_VENDOR])
    return sample


def main():
    from google.colab import drive

    drive.mount("/content/drive", force_remount=False)

    for name in ("model", "tokenizer"):
        if name in globals():
            del globals()[name]
    gc.collect()
    torch.cuda.empty_cache()

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="unsloth/Qwen2.5-1.5B-Instruct",
        max_seq_length=MAX_SEQ,
        dtype=None,
        load_in_4bit=True,
    )
    model.load_adapter(V3_PATH, adapter_name="v3")
    model.load_adapter(V1_PATH, adapter_name="v1")
    FastLanguageModel.for_inference(model)
    print("loaded cascade: v3 + regex + v1")

    sample = build_sample(Path(VAL_PATH))
    print("candidate invoices", len(sample))

    stats = {
        k: {"ok": 0, "missing": 0, "wrong": 0, "n": 0}
        for k in SCORE_FIELDS + ["line_count"]
    }
    schema_pass = 0
    strict_ok = 0
    scored = 0
    skipped_long = 0
    parse_fail = 0
    fallback_counts = defaultdict(int)
    rows_out = []

    for i, row in enumerate(sample, 1):
        ocr = (row.get("ocr_text") or "").strip()
        prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr
        text = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        )
        ntok = len(tokenizer(text, add_special_tokens=False)["input_ids"])
        if ntok > MAX_PROMPT_TOKENS:
            skipped_long += 1
            continue

        pred, used, raw = run_pipeline(model, tokenizer, ocr)
        for u in used:
            fallback_counts[u] += 1

        ok_schema, problems = schema_ok(pred)
        if ok_schema:
            schema_pass += 1
        if pred.get("invoice_summary") == {} and not parse_json(raw):
            parse_fail += 1

        gold = row.get("gemini_json") or {}
        gs = gold.get("invoice_summary") or {}
        ps = pred.get("invoice_summary") or {}

        field_row = {}
        for field in SCORE_FIELDS:
            g, p = norm(gs.get(field)), norm(ps.get(field))
            stats[field]["n"] += 1
            if is_blank(ps.get(field)):
                stats[field]["missing"] += 1
                status = "missing"
            elif p == g:
                stats[field]["ok"] += 1
                status = "ok"
            else:
                stats[field]["wrong"] += 1
                status = "wrong"
            field_row[field] = status

        gc_, pc_ = line_count(gold), line_count(pred)
        stats["line_count"]["n"] += 1
        if pc_ is None:
            stats["line_count"]["missing"] += 1
            field_row["line_count"] = "missing"
        elif pc_ == gc_:
            stats["line_count"]["ok"] += 1
            field_row["line_count"] = "ok"
        else:
            stats["line_count"]["wrong"] += 1
            field_row["line_count"] = "wrong"

        if all(
            (not is_blank(ps.get(k))) and norm(ps.get(k)) == norm(gs.get(k))
            for k in STRICT_FIELDS
        ):
            strict_ok += 1

        scored += 1
        rows_out.append(
            {
                "blob_path": row.get("blob_path"),
                "vendor": row.get("vendor"),
                "prompt_tokens": ntok,
                "schema_ok": ok_schema,
                "schema_problems": problems,
                "fallback_used": used,
                "fields": field_row,
            }
        )
        if scored % 5 == 0:
            print(f"scored {scored} | skipped_long {skipped_long}")

    total_ok = sum(stats[k]["ok"] for k in stats)
    total_n = sum(stats[k]["n"] for k in stats)
    overall = 100 * total_ok / max(total_n, 1)
    strict_pct = 100 * strict_ok / max(scored, 1)
    schema_pct = 100 * schema_pass / max(scored, 1)

    print("\n========== PIPELINE VALIDATION ==========")
    print("pipeline: v3 -> regex -> v1 header")
    print("scored invoices", scored)
    print("skipped (too long for this version)", skipped_long)
    print(f"overall field accuracy {overall:.1f}%")
    print(
        f"strict (invoice_no + both GSTINs + tax + total) {strict_pct:.1f}%"
    )
    print(f"schema valid {schema_pct:.1f}%")
    print(f"json parse fail (empty fallback obj) {parse_fail}")
    print("\nfallback usage:")
    if fallback_counts:
        for k, v in sorted(fallback_counts.items(), key=lambda x: -x[1]):
            print(f"  {k}: {v}")
    else:
        print("  (none)")

    print(f"\n{'field':18} {'accuracy':>8} {'missing':>8} {'wrong':>8}")
    for field in sorted(stats, key=lambda k: stats[k]["ok"] / max(stats[k]["n"], 1)):
        s = stats[field]
        n = max(s["n"], 1)
        print(
            f"{field:18} {100 * s['ok'] / n:7.1f}% "
            f"{100 * s['missing'] / n:7.1f}% "
            f"{100 * s['wrong'] / n:7.1f}%"
        )

    report = {
        "pipeline": "v3 -> regex -> v1 header",
        "scored": scored,
        "skipped_long": skipped_long,
        "overall_field_accuracy_pct": round(overall, 2),
        "strict_pct": round(strict_pct, 2),
        "schema_valid_pct": round(schema_pct, 2),
        "parse_fail": parse_fail,
        "fallback_counts": dict(fallback_counts),
        "fields": {
            k: {
                "accuracy_pct": round(100 * v["ok"] / max(v["n"], 1), 2),
                "missing_pct": round(100 * v["missing"] / max(v["n"], 1), 2),
                "wrong_pct": round(100 * v["wrong"] / max(v["n"], 1), 2),
                "n": v["n"],
            }
            for k, v in stats.items()
        },
        "rows": rows_out,
        "scope_note": ( `
            "Invoices with prompt tokens > "
            f"{MAX_PROMPT_TOKENS} are skipped; this version targets normal-length "
            "PDF Plumber OCR only."
        ),
    }
    Path(OUT_PATH).write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print("\nsaved report", OUT_PATH)
    print("=========================================")


if __name__ == "__main__":
    main()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==((====))==  Unsloth 2026.9.5: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA L4. Num GPUs = 1. Max memory: 22.034 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.9. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.13/dist-packages/peft/tuners/tuners_utils.py:305: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

loaded cascade: v3 + regex + v1
candidate invoices 24
scored 5 | skipped_long 0
scored 10 | skipped_long 0
scored 15 | skipped_long 2
scored 20 | skipped_long 2

========== PIPELINE VALIDATION ==========
pipeline: v3 -> regex -> v1 header
scored invoices 21
skipped (too long for this version) 3
overall field accuracy 77.6%
strict (invoice_no + both GSTINs + tax + total) 19.0%
schema valid 95.2%
json parse fail (empty fallback obj) 0

fallback usage:
  regex:vendor_gstin: 8
  v1:vendor: 7
  regex:customer_gstin: 1
  regex:irn: 1

field              accuracy  missing    wrong
customer_gstin        38.1%     0.0%    61.9%
irn                   52.4%     0.0%    47.6%
customer              76.2%     4.8%    19.0%
tax                   76.2%    23.8%     0.0%
total                 76.2%     4.8%    19.0%
invoice_no            85.7%     4.8%     9.5%
vendor_gstin          85.7%     0.0%    14.3%
invoice_date          95.2%     4.8%     0.0%
vendor                95.2%     0.0%     4.8%
line_count            95.2%     4.8%     0.0%

saved report /content/drive/MyDrive/pipeline_validation_report.json
=========================================

In [ ]:
"""
Pre-production validation for the invoice cascade:
  v3 (full JSON) -> regex (GSTIN/IRN) -> v1 (header fill-if-blank)

Run in Colab with Drive mounted and a GPU.
Does not train. Does not write Azure. Does not touch SAP.
"""

from __future__ import annotations

import gc
import json
import random
import re
from collections import defaultdict
from copy import deepcopy
from pathlib import Path

import torch
from unsloth import FastLanguageModel

# ---------- paths (Colab Drive) ----------
V3_PATH = "/content/drive/MyDrive/invoice_lora_v3"
V1_PATH = "/content/drive/MyDrive/invoice_lora"
VAL_PATH = "/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl"
OUT_PATH = "/content/drive/MyDrive/pipeline_validation_report.json"

MAX_SEQ = 8192
# Skip invoices whose prompt is too long for this version
MAX_PROMPT_TOKENS = 6000
# How many invoices per held-out vendor (same style as earlier scores)
PER_VENDOR = 2
MAX_VENDORS = 12
SEED = 3407

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)
HEADER_FIELDS = ["vendor", "vendor_gstin", "tax", "irn"]
SCORE_FIELDS = [
    "invoice_no",
    "invoice_date",
    "vendor",
    "customer",
    "vendor_gstin",
    "customer_gstin",
    "tax",
    "total",
    "irn",
]
STRICT_FIELDS = ["invoice_no", "vendor_gstin", "customer_gstin", "tax", "total"]

GSTIN_RE = re.compile(r"\b\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9]Z[A-Z0-9]\b", re.I)
IRN_RE = re.compile(r"\b[a-fA-F0-9]{64}\b")
# Reject tiny/stub OCR (splitextract ocr_quality idea / BUG-002)
MIN_OCR_CHARS = 200
SUMMARY_REQUIRED = {
    "invoice_no",
    "invoice_date",
    "vendor",
    "customer",
    "vendor_gstin",
    "customer_gstin",
    "customer_address",
    "irn",
    "tax",
    "total",
}


def is_blank(v) -> bool:
    if v is None:
        return True
    if isinstance(v, str):
        t = v.strip()
        if not t:
            return True
        if t.lower() in {"none", "null", "nan", "n/a", "-"}:
            return True
    return False


def norm(v) -> str:
    if v is None:
        return ""
    return re.sub(r"\s+", " ", str(v).strip().upper())


def clean_gstin(gstin_str) -> str | None:
    """From splitextract: normalize OCR GSTIN and validate shape."""
    if not gstin_str:
        return None
    cleaned = re.sub(r"[\s\-]", "", str(gstin_str).upper().strip())
    cleaned = cleaned.replace("l", "1")
    pat = r"^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z0-9]Z[A-Z0-9]$"
    if re.match(pat, cleaned):
        return cleaned
    fixed = list(cleaned)
    for pos in (0, 1, 7, 8, 9, 10):
        if pos < len(fixed) and fixed[pos] == "O":
            fixed[pos] = "0"
    fixed_s = "".join(fixed)
    if re.match(pat, fixed_s):
        return fixed_s
    return None


def valid_gstin(v) -> tuple[bool, str]:
    g = clean_gstin(v) or ""
    return bool(g), g


def gstins_from_ocr(ocr_text: str) -> list[str]:
    """Distinct GSTINs in OCR order (word-boundary, not compacted)."""
    found: list[str] = []
    for m in GSTIN_RE.finditer(ocr_text or ""):
        g = clean_gstin(m.group())
        if g and g not in found:
            found.append(g)
    return found


def _gstin_near_label(ocr: str, gstin: str, labels: tuple[str, ...]) -> bool:
    """True if a label appears within ~80 chars before this GSTIN."""
    up = (ocr or "").upper()
    g = gstin.upper()
    idx = up.find(g)
    if idx < 0:
        return False
    window = up[max(0, idx - 80) : idx]
    return any(lab in window for lab in labels)


def extract_net_amount_from_ocr(ocr_text: str) -> str | None:
    """From splitextract: NET AMOUNT / GRAND TOTAL / payable (largest sane)."""
    if not ocr_text:
        return None
    patterns = [
        r"NET\s*AMOUNT[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
        r"GRAND\s*TOTAL[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
        r"Invoice\s+Total[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
        r"TOTAL\s+AMOUNT[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
        r"(?:Amount\s+)?Payable[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
        r"BILL\s+AMOUNT[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
    ]
    values: list[float] = []
    for pattern in patterns:
        for match in re.finditer(pattern, ocr_text, re.IGNORECASE):
            pre = ocr_text[match.start() : match.start(1)]
            if re.search(r"\bIRN\b", pre, re.IGNORECASE):
                continue
            try:
                value = float(match.group(1).replace(",", ""))
            except ValueError:
                continue
            if value > 100:
                values.append(value)
    if not values:
        return None
    unique = sorted(set(values), reverse=True)
    largest = unique[0]
    if len(unique) >= 2:
        second = unique[1]
        if largest > second * 50 and second > 100:
            ratio = largest / second
            if 90 <= ratio <= 110:
                largest = second
    return f"{largest:.2f}"


def extract_tax_from_ocr(ocr_text: str) -> str | None:
    """Fill blank tax from TOTAL GST / CGST+SGST / IGST labels."""
    if not ocr_text:
        return None
    patterns = [
        r"(?:TOTAL\s*GST|GST\s*AMOUNT|TAX\s*AMOUNT)[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
        r"\bIGST[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)",
    ]
    for pattern in patterns:
        m = re.search(pattern, ocr_text, re.IGNORECASE)
        if not m:
            continue
        try:
            value = float(m.group(1).replace(",", ""))
        except ValueError:
            continue
        if value >= 0:
            return f"{value:.2f}"

    cgst = re.search(r"\bCGST[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)", ocr_text, re.I)
    sgst = re.search(r"\bSGST[^0-9]{0,15}([0-9][0-9,]*(?:\.\d{1,2})?)", ocr_text, re.I)
    if cgst and sgst:
        try:
            total = float(cgst.group(1).replace(",", "")) + float(
                sgst.group(1).replace(",", "")
            )
            if total >= 0:
                return f"{total:.2f}"
        except ValueError:
            pass
    return None


def extract_invoice_no_from_ocr(ocr_text: str) -> str | None:
    """Light invoice-no pull; skip GSTIN-like and phone-like tokens."""
    if not ocr_text:
        return None
    patterns = [
        r"\bINV(?:OICE)?\.?\s*NO\.?\s*[:\-]?\s*([A-Z0-9][A-Z0-9/\-]{2,24})",
        r"\bINVOICE\s*(?:NO\.?|NUMBER|#)?\s*[:\-]?\s*([A-Z0-9][A-Z0-9/\-]{2,24})",
        r"\bBILL\s*NO\.?\s*[:\-]?\s*([A-Z0-9][A-Z0-9/\-]{2,24})",
    ]
    for pattern in patterns:
        for m in re.finditer(pattern, ocr_text, re.IGNORECASE):
            cand = m.group(1).strip().rstrip(".,;")
            if clean_gstin(cand):
                continue
            digits = re.sub(r"\D", "", cand)
            if len(digits) == 10 and digits[0] in "6789":
                continue
            if re.fullmatch(r"\d{6,8}", cand):  # likely HSN
                continue
            return cand
    return None


def parse_json(text):
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None


def line_count(obj):
    if not isinstance(obj, dict):
        return None
    li = obj.get("line_items")
    if isinstance(li, dict) and isinstance(li.get("items"), list):
        return len(li["items"])
    if isinstance(li, list):
        return len(li)
    return None


def schema_ok(obj) -> tuple[bool, list[str]]:
    problems = []
    if not isinstance(obj, dict):
        return False, ["not_a_dict"]
    if "invoice_summary" not in obj:
        problems.append("missing_invoice_summary")
    if "line_items" not in obj:
        problems.append("missing_line_items")
    summary = obj.get("invoice_summary")
    if not isinstance(summary, dict):
        problems.append("invoice_summary_not_dict")
    else:
        missing = SUMMARY_REQUIRED - set(summary.keys())
        if missing:
            problems.append("summary_missing_keys:" + ",".join(sorted(missing)))
    li = obj.get("line_items")
    if isinstance(li, dict):
        if not isinstance(li.get("items"), list):
            problems.append("line_items.items_not_list")
    elif not isinstance(li, list):
        problems.append("line_items_bad_type")
    return len(problems) == 0, problems


def generate(model, tokenizer, ocr_text, max_new_tokens=2048):
    prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr_text.strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False,
        use_cache=True,
    )
    raw = tokenizer.decode(
        out[0][inputs["input_ids"].shape[-1] :],
        skip_special_tokens=True,
    )
    return raw, parse_json(raw)


def regex_fill(summary, ocr_text, used):
    """
    Post-process with splitextract-style OCR regex.
    - clean / assign GSTINs (including customer==vendor poison fix)
    - fill blank IRN, total, tax, invoice_no from OCR labels
    Never invent a GSTIN that is not in OCR.
    """
    summary = dict(summary or {})
    ocr = ocr_text or ""
    found = gstins_from_ocr(ocr)

    vendor_labels = (
        "VENDOR GSTIN",
        "SUPPLIER GSTIN",
        "SELLER GSTIN",
        "FROM GSTIN",
        "GSTIN OF SUPPLIER",
        "GSTIN:",
        "GST NO",
        "GSTNO",
    )
    customer_labels = (
        "CUSTOMER GSTIN",
        "BUYER GSTIN",
        "BILL TO GSTIN",
        "SHIP TO GSTIN",
        "CONSIGNEE GSTIN",
        "GSTIN OF RECIPIENT",
        "GSTIN OF BUYER",
        "TO GSTIN",
    )

    ok_v, cur_v = valid_gstin(summary.get("vendor_gstin"))
    ok_c, cur_c = valid_gstin(summary.get("customer_gstin"))

    # Prefer label-anchored GSTIN when present in OCR
    labeled_vendor = next(
        (g for g in found if _gstin_near_label(ocr, g, vendor_labels)), None
    )
    labeled_customer = next(
        (g for g in found if _gstin_near_label(ocr, g, customer_labels) and g != labeled_vendor),
        None,
    )

    if labeled_vendor and (not ok_v or cur_v not in found):
        summary["vendor_gstin"] = labeled_vendor
        used.append("regex:vendor_gstin")
        ok_v, cur_v = True, labeled_vendor
    elif (not ok_v) and found:
        summary["vendor_gstin"] = found[0]
        used.append("regex:vendor_gstin")
        ok_v, cur_v = True, found[0]
    elif ok_v and cur_v not in found and found:
        # Model GSTIN not grounded in OCR -> replace
        summary["vendor_gstin"] = labeled_vendor or found[0]
        used.append("regex:vendor_gstin_ungrounded")
        ok_v, cur_v = True, summary["vendor_gstin"]

    if labeled_customer and (not ok_c or cur_c == cur_v or cur_c not in found):
        summary["customer_gstin"] = labeled_customer
        used.append("regex:customer_gstin")
        ok_c, cur_c = True, labeled_customer
    elif (not ok_c) and len(found) >= 2:
        other = next((g for g in found if g != cur_v), found[1])
        summary["customer_gstin"] = other
        used.append("regex:customer_gstin")
        ok_c, cur_c = True, other
    elif ok_c and cur_c == cur_v and len(found) >= 2:
        # Poisoned duplicate: both set to vendor; pick the other OCR GSTIN
        other = next((g for g in found if g != cur_v), None)
        if other:
            summary["customer_gstin"] = other
            used.append("regex:customer_gstin_dedupe")
            ok_c, cur_c = True, other
    elif ok_c and cur_c not in found and len(found) >= 2:
        other = next((g for g in found if g != cur_v), found[-1])
        summary["customer_gstin"] = other
        used.append("regex:customer_gstin_ungrounded")

    if is_blank(summary.get("irn")):
        m = IRN_RE.search(ocr)
        if m:
            summary["irn"] = m.group().lower()
            used.append("regex:irn")

    if is_blank(summary.get("total")):
        amt = extract_net_amount_from_ocr(ocr)
        if amt:
            summary["total"] = amt
            used.append("regex:total")

    if is_blank(summary.get("tax")):
        tax = extract_tax_from_ocr(ocr)
        if tax:
            summary["tax"] = tax
            used.append("regex:tax")

    if is_blank(summary.get("invoice_no")):
        inv = extract_invoice_no_from_ocr(ocr)
        if inv:
            summary["invoice_no"] = inv
            used.append("regex:invoice_no")

    return summary


def needs_header_fallback(summary) -> bool:
    summary = summary or {}
    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(summary.get(k))
            if not ok:
                return True
        elif is_blank(summary.get(k)):
            return True
    return False


def merge_header_from_v1(base_obj, v1_obj, used):
    out = (
        deepcopy(base_obj)
        if isinstance(base_obj, dict)
        else {"invoice_summary": {}, "line_items": None}
    )
    s = out.setdefault("invoice_summary", {})
    s1 = ((v1_obj or {}).get("invoice_summary") or {}) if isinstance(v1_obj, dict) else {}

    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(s.get(k))
            ok1, g1 = valid_gstin(s1.get(k))
            if (not ok) and ok1:
                s[k] = g1
                used.append(f"v1:{k}")
        else:
            if is_blank(s.get(k)) and not is_blank(s1.get(k)):
                s[k] = s1[k]
                used.append(f"v1:{k}")

    out["invoice_summary"] = s
    return out


def run_pipeline(model, tokenizer, ocr_text):
    used = []
    ocr = (ocr_text or "").strip()
    if len(ocr) < MIN_OCR_CHARS:
        used.append("error:EMPTY_OCR")
        return (
            {"invoice_summary": {}, "line_items": None, "error": "EMPTY_OCR"},
            used,
            "",
        )

    model.set_adapter("v3")
    raw_v3, obj_v3 = generate(model, tokenizer, ocr)
    if not isinstance(obj_v3, dict):
        obj_v3 = {"invoice_summary": {}, "line_items": None}

    summary = dict(obj_v3.get("invoice_summary") or {})
    summary = regex_fill(summary, ocr, used)
    obj_v3["invoice_summary"] = summary

    if needs_header_fallback(summary):
        model.set_adapter("v1")
        _, obj_v1 = generate(model, tokenizer, ocr)
        obj_v3 = merge_header_from_v1(obj_v3, obj_v1, used)
        # Second regex pass: fix GSTIN dedupe / totals after v1
        summary = regex_fill(dict(obj_v3.get("invoice_summary") or {}), ocr, used)
        obj_v3["invoice_summary"] = summary

    return obj_v3, used, raw_v3


def build_sample(val_path: Path):
    by_vendor = defaultdict(list)
    with val_path.open(encoding="utf-8") as f:
        for line in f:
            row = json.loads(line)
            by_vendor[row.get("vendor") or "UNKNOWN"].append(row)

    random.seed(SEED)
    sample = []
    for _, rows in sorted(by_vendor.items(), key=lambda x: -len(x[1])):
        if len(sample) >= MAX_VENDORS * PER_VENDOR:
            break
        random.shuffle(rows)
        sample.extend(rows[:PER_VENDOR])
    return sample


def main():
    from google.colab import drive

    drive.mount("/content/drive", force_remount=False)

    for name in ("model", "tokenizer"):
        if name in globals():
            del globals()[name]
    gc.collect()
    torch.cuda.empty_cache()

    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name="unsloth/Qwen2.5-1.5B-Instruct",
        max_seq_length=MAX_SEQ,
        dtype=None,
        load_in_4bit=True,
    )
    model.load_adapter(V3_PATH, adapter_name="v3")
    model.load_adapter(V1_PATH, adapter_name="v1")
    FastLanguageModel.for_inference(model)
    print("loaded cascade: v3 + regex + v1")

    sample = build_sample(Path(VAL_PATH))
    print("candidate invoices", len(sample))

    stats = {
        k: {"ok": 0, "missing": 0, "wrong": 0, "n": 0}
        for k in SCORE_FIELDS + ["line_count"]
    }
    schema_pass = 0
    strict_ok = 0
    scored = 0
    skipped_long = 0
    parse_fail = 0
    fallback_counts = defaultdict(int)
    rows_out = []

    for i, row in enumerate(sample, 1):
        ocr = (row.get("ocr_text") or "").strip()
        prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr
        text = tokenizer.apply_chat_template(
            [{"role": "user", "content": prompt}],
            tokenize=False,
            add_generation_prompt=True,
        )
        ntok = len(tokenizer(text, add_special_tokens=False)["input_ids"])
        if ntok > MAX_PROMPT_TOKENS:
            skipped_long += 1
            continue

        pred, used, raw = run_pipeline(model, tokenizer, ocr)
        for u in used:
            fallback_counts[u] += 1

        ok_schema, problems = schema_ok(pred)
        if ok_schema:
            schema_pass += 1
        if pred.get("invoice_summary") == {} and not parse_json(raw):
            parse_fail += 1

        gold = row.get("gemini_json") or {}
        gs = gold.get("invoice_summary") or {}
        ps = pred.get("invoice_summary") or {}

        field_row = {}
        for field in SCORE_FIELDS:
            g, p = norm(gs.get(field)), norm(ps.get(field))
            stats[field]["n"] += 1
            if is_blank(ps.get(field)):
                stats[field]["missing"] += 1
                status = "missing"
            elif p == g:
                stats[field]["ok"] += 1
                status = "ok"
            else:
                stats[field]["wrong"] += 1
                status = "wrong"
            field_row[field] = status

        gc_, pc_ = line_count(gold), line_count(pred)
        stats["line_count"]["n"] += 1
        if pc_ is None:
            stats["line_count"]["missing"] += 1
            field_row["line_count"] = "missing"
        elif pc_ == gc_:
            stats["line_count"]["ok"] += 1
            field_row["line_count"] = "ok"
        else:
            stats["line_count"]["wrong"] += 1
            field_row["line_count"] = "wrong"

        if all(
            (not is_blank(ps.get(k))) and norm(ps.get(k)) == norm(gs.get(k))
            for k in STRICT_FIELDS
        ):
            strict_ok += 1

        scored += 1
        rows_out.append(
            {
                "blob_path": row.get("blob_path"),
                "vendor": row.get("vendor"),
                "prompt_tokens": ntok,
                "schema_ok": ok_schema,
                "schema_problems": problems,
                "fallback_used": used,
                "fields": field_row,
            }
        )
        if scored % 5 == 0:
            print(f"scored {scored} | skipped_long {skipped_long}")

    total_ok = sum(stats[k]["ok"] for k in stats)
    total_n = sum(stats[k]["n"] for k in stats)
    overall = 100 * total_ok / max(total_n, 1)
    strict_pct = 100 * strict_ok / max(scored, 1)
    schema_pct = 100 * schema_pass / max(scored, 1)

    print("\n========== PIPELINE VALIDATION ==========")
    print("pipeline: v3 -> regex -> v1 header")
    print("scored invoices", scored)
    print("skipped (too long for this version)", skipped_long)
    print(f"overall field accuracy {overall:.1f}%")
    print(
        f"strict (invoice_no + both GSTINs + tax + total) {strict_pct:.1f}%"
    )
    print(f"schema valid {schema_pct:.1f}%")
    print(f"json parse fail (empty fallback obj) {parse_fail}")
    print("\nfallback usage:")
    if fallback_counts:
        for k, v in sorted(fallback_counts.items(), key=lambda x: -x[1]):
            print(f"  {k}: {v}")
    else:
        print("  (none)")

    print(f"\n{'field':18} {'accuracy':>8} {'missing':>8} {'wrong':>8}")
    for field in sorted(stats, key=lambda k: stats[k]["ok"] / max(stats[k]["n"], 1)):
        s = stats[field]
        n = max(s["n"], 1)
        print(
            f"{field:18} {100 * s['ok'] / n:7.1f}% "
            f"{100 * s['missing'] / n:7.1f}% "
            f"{100 * s['wrong'] / n:7.1f}%"
        )

    report = {
        "pipeline": "v3 -> regex -> v1 header",
        "scored": scored,
        "skipped_long": skipped_long,
        "overall_field_accuracy_pct": round(overall, 2),
        "strict_pct": round(strict_pct, 2),
        "schema_valid_pct": round(schema_pct, 2),
        "parse_fail": parse_fail,
        "fallback_counts": dict(fallback_counts),
        "fields": {
            k: {
                "accuracy_pct": round(100 * v["ok"] / max(v["n"], 1), 2),
                "missing_pct": round(100 * v["missing"] / max(v["n"], 1), 2),
                "wrong_pct": round(100 * v["wrong"] / max(v["n"], 1), 2),
                "n": v["n"],
            }
            for k, v in stats.items()
        },
        "rows": rows_out,
        "scope_note": (
            "Invoices with prompt tokens > "
            f"{MAX_PROMPT_TOKENS} are skipped; this version targets normal-length "
            "PDF Plumber OCR only."
        ),
    }
    Path(OUT_PATH).write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print("\nsaved report", OUT_PATH)
    print("=========================================")


if __name__ == "__main__":
    main()

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==((====))==  Unsloth 2026.9.5: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    NVIDIA A100-SXM4-80GB. Num GPUs = 1. Max memory: 79.251 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 8.0. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

/usr/local/lib/python3.13/dist-packages/peft/tuners/tuners_utils.py:305: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

loaded cascade: v3 + regex + v1
candidate invoices 24
scored 5 | skipped_long 0
scored 10 | skipped_long 0
scored 15 | skipped_long 2
scored 20 | skipped_long 2

========== PIPELINE VALIDATION ==========
pipeline: v3 -> regex -> v1 header
scored invoices 21
skipped (too long for this version) 3
overall field accuracy 80.0%
strict (invoice_no + both GSTINs + tax + total) 28.6%
schema valid 95.2%
json parse fail (empty fallback obj) 0

fallback usage:
  regex:customer_gstin_dedupe: 10
  regex:vendor_gstin: 7
  v1:vendor: 6
  regex:customer_gstin: 2
  regex:irn: 1
  regex:invoice_no: 1

field              accuracy  missing    wrong
irn                   57.1%     0.0%    42.9%
customer_gstin        66.7%     0.0%    33.3%
tax                   71.4%    23.8%     4.8%
customer              76.2%     4.8%    19.0%
vendor_gstin          76.2%     0.0%    23.8%
total                 76.2%     4.8%    19.0%
invoice_no            90.5%     0.0%     9.5%
invoice_date          95.2%     4.8%     0.0%
vendor                95.2%     0.0%     4.8%
line_count            95.2%     4.8%     0.0%

saved report /content/drive/MyDrive/pipeline_validation_report.json
=========================================

In [ ]:
# IRN script (run AFTER v3 + regex + v1). Does not change regex / v1 / v3.
# Any 64-character hexadecimal string is treated as IRN.

import re

IRN_LENGTH = 64
HEX_CHARS = set("0123456789abcdefABCDEF")
IRN_CONTIGUOUS_RE = re.compile(r"[a-fA-F0-9]{64}")
IRN_GAPPED_RE = re.compile(r"[a-fA-F0-9](?:[\s\-]*[a-fA-F0-9]){63}")
IRN_LABEL_RE = re.compile(r"\bIRN(?:\s*(?:NO\.?|NUMBER|#))?\s*[:.,\-]?\s*", re.I)
_STOP_FIELD_RE = re.compile(
    r"\b(?:ACK(?:\.?\s*NO)?|GSTIN|GST\s*NO|DL\.?\s*NO|CIN|"
    r"INV(?:OICE)?\s*(?:NO|NUM)|ORDER\s*DATE|BILL\s*DT|"
    r"HSN|S\.?\s*N\.?)\b",
    re.I,
)


def _compact_hex(text):
    return "".join(ch.lower() for ch in text if ch in HEX_CHARS)


def _collect_hex_allowing_gaps(text):
    chars = []
    for ch in text:
        if ch in HEX_CHARS:
            chars.append(ch.lower())
            if len(chars) == IRN_LENGTH:
                break
        elif ch.isspace() or ch in "-:.,":
            continue
        else:
            break
    return "".join(chars)


def _line_is_hex_continuation(line):
    stripped = line.strip()
    if not stripped or stripped[0] not in HEX_CHARS:
        return False
    extra = sum(1 for ch in stripped if ch.isalpha() and ch.lower() not in "abcdef")
    return extra < 3


def find_irn_near_label(ocr_text):
    text = ocr_text or ""
    for match in IRN_LABEL_RE.finditer(text):
        rest = text[match.end():]
        stop = _STOP_FIELD_RE.search(rest)
        region = rest[:stop.start()] if stop else rest[:320]
        hexed = _collect_hex_allowing_gaps(region)
        if len(hexed) == IRN_LENGTH:
            return hexed
        lines = rest.splitlines()
        assembled = _collect_hex_allowing_gaps(lines[0] if lines else "")
        for line in lines[1:5]:
            if not line.strip():
                continue
            if not _line_is_hex_continuation(line):
                break
            assembled += _compact_hex(line)
            if len(assembled) >= IRN_LENGTH:
                return assembled[:IRN_LENGTH]
        if len(assembled) == IRN_LENGTH:
            return assembled
    return None


def extract_irn_64(ocr_text):
    text = ocr_text or ""
    found, seen = [], set()

    def add(v):
        if v and v not in seen:
            seen.add(v)
            found.append(v)

    add(find_irn_near_label(text))
    for m in IRN_CONTIGUOUS_RE.finditer(text):
        add(m.group().lower())
    for m in IRN_GAPPED_RE.finditer(text):
        add(_compact_hex(m.group()))
    return found[0] if found else None


def apply_irn_from_script(summary, ocr_text, used=None):
    out = dict(summary or {})
    used = used if used is not None else []
    found = extract_irn_64(ocr_text)
    if not found:
        return out
    current = out.get("irn")
    current_text = current.strip().lower() if isinstance(current, str) else ""
    if current_text != found:
        used.append("script:irn")
    out["irn"] = found
    return out


# Use on pipeline output (v3 -> regex -> v1 stays the same; IRN comes from this script at the end):
#   result = run_pipeline(model, tokenizer, ocr_text)
#   s = result["final"].setdefault("invoice_summary", {})
#   result["final"]["invoice_summary"] = apply_irn_from_script(s, ocr_text, result["fallback_used"])
#   print(result["final"]["invoice_summary"].get("irn"))

ocr_demo = "IRN:670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034cAck.No.:1326"
print(extract_irn_64(ocr_demo))

670a20b56d4546b638e56007520543bb5746a73542f614cf03b52cbeb417034c

In [ ]:
# IRN accuracy: regex vs 64-hex script (final pipeline overlay)
# Run after Drive is mounted. Does not change v3 / regex / v1.

import json
import re
from collections import Counter
from pathlib import Path

IRN_LENGTH = 64
HEX_CHARS = set("0123456789abcdefABCDEF")
IRN_RE = re.compile(r"\b[a-fA-F0-9]{64}\b")  # existing regex (unchanged)
IRN_CONTIGUOUS_RE = re.compile(r"[a-fA-F0-9]{64}")
IRN_GAPPED_RE = re.compile(r"[a-fA-F0-9](?:[\s\-]*[a-fA-F0-9]){63}")
IRN_LABEL_RE = re.compile(r"\bIRN(?:\s*(?:NO\.?|NUMBER|#))?\s*[:.,\-]?\s*", re.I)
_STOP_FIELD_RE = re.compile(
    r"\b(?:ACK(?:\.?\s*NO)?|GSTIN|GST\s*NO|DL\.?\s*NO|CIN|"
    r"INV(?:OICE)?\s*(?:NO|NUM)|ORDER\s*DATE|BILL\s*DT|HSN|S\.?\s*N\.?)\b",
    re.I,
)
BLANK = {"", "none", "null", "nan", "n/a", "-", "na", "nil"}


def _compact_hex(text):
    return "".join(ch.lower() for ch in text if ch in HEX_CHARS)


def _collect_hex_allowing_gaps(text):
    chars = []
    for ch in text:
        if ch in HEX_CHARS:
            chars.append(ch.lower())
            if len(chars) == IRN_LENGTH:
                break
        elif ch.isspace() or ch in "-:.,":
            continue
        else:
            break
    return "".join(chars)


def extract_irn_64(ocr_text):
    text = ocr_text or ""
    found, seen = [], set()

    def add(v):
        if v and v not in seen:
            seen.add(v)
            found.append(v)

    for match in IRN_LABEL_RE.finditer(text):
        rest = text[match.end():]
        stop = _STOP_FIELD_RE.search(rest)
        region = rest[: stop.start()] if stop else rest[:320]
        hexed = _collect_hex_allowing_gaps(region)
        if len(hexed) == IRN_LENGTH:
            add(hexed)
            break
        lines = rest.splitlines()
        assembled = _collect_hex_allowing_gaps(lines[0] if lines else "")
        for line in lines[1:5]:
            if not line.strip():
                continue
            stripped = line.strip()
            extra = sum(1 for ch in stripped if ch.isalpha() and ch.lower() not in "abcdef")
            if extra >= 3 or not stripped or stripped[0] not in HEX_CHARS:
                break
            assembled += _compact_hex(line)
            if len(assembled) >= IRN_LENGTH:
                add(assembled[:IRN_LENGTH])
                break
        if len(assembled) == IRN_LENGTH:
            add(assembled)
            break
    for m in IRN_CONTIGUOUS_RE.finditer(text):
        add(m.group().lower())
    for m in IRN_GAPPED_RE.finditer(text):
        add(_compact_hex(m.group()))
    return found[0] if found else None


def gold_irn(row):
    summary = ((row.get("gemini_json") or {}).get("invoice_summary") or {})
    value = summary.get("irn")
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.lower() in BLANK:
        return None
    compact = _compact_hex(text)
    return compact if len(compact) == 64 else text.lower()


def regex_irn(ocr):
    m = IRN_RE.search(ocr or "")
    return m.group().lower() if m else None


def gold_in_ocr(ocr, gold):
    if not gold or len(gold) != 64:
        return False
    return gold in re.sub(r"[^a-fA-F0-9]", "", ocr or "").lower()


def score(rows, pred_fn):
    c = Counter()
    gold_n = match_gold = 0
    for row in rows:
        ocr = row.get("ocr_text") or ""
        g = gold_irn(row)
        p = pred_fn(ocr)
        c["n"] += 1
        if g is None and p is None:
            c["both_blank"] += 1
        elif g is None:
            c["false_positive"] += 1
        elif p is None:
            c["missing"] += 1
        elif p == g:
            c["match"] += 1
        else:
            c["wrong"] += 1
        if g is not None:
            gold_n += 1
            if p == g:
                match_gold += 1
            if gold_in_ocr(ocr, g):
                c["gold_in_ocr"] += 1
                if p == g:
                    c["match_in_ocr"] += 1
    n = c["n"] or 1
    return {
        "invoices": c["n"],
        "gold_irn": gold_n,
        "match": c["match"],
        "missing": c["missing"],
        "wrong": c["wrong"],
        "both_blank": c["both_blank"],
        "false_positive": c["false_positive"],
        "acc_when_gold": round(100 * match_gold / gold_n, 2) if gold_n else None,
        "acc_all": round(100 * (c["match"] + c["both_blank"]) / n, 2),
        "acc_when_in_ocr": round(100 * c["match_in_ocr"] / c["gold_in_ocr"], 2) if c["gold_in_ocr"] else None,
    }


def load_jsonl(path):
    rows = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


candidates = [
    Path("/content/drive/MyDrive/training_export"),
    Path("/content/drive/MyDrive/training_export/training_export"),
    Path(r"C:\Users\Prerana Bhalerao\OneDrive\Desktop\model train\training_export (2)\training_export"),
]
data_root = next((p for p in candidates if p.exists()), None)
assert data_root is not None, "Mount Drive or set training_export path"
print("data_root:", data_root)

val_path = data_root / "pdfplumber_val.jsonl"
train_files = sorted(p for p in data_root.glob("pdfplumber_train_batch_*.jsonl"))
splits = {
    "val": load_jsonl(val_path) if val_path.exists() else [],
    "train": [],
}
for p in train_files:
    print("loading", p.name)
    splits["train"].extend(load_jsonl(p))
splits["all"] = splits["val"] + splits["train"]

methods = [("regex_only", regex_irn), ("pipeline_irn_script", extract_irn_64)]
print("\n{:<8} {:>8} {:>8} {:>12} {:>12} {:>12} {:>14}".format(
    "split", "n", "gold", "regex_acc", "script_acc", "script_match", "acc_if_in_ocr"
))
print("-" * 86)
for name, rows in splits.items():
    stats = {m: score(rows, fn) for m, fn in methods}
    r, s = stats["regex_only"], stats["pipeline_irn_script"]
    print("{:<8} {:>8} {:>8} {:>11}% {:>11}% {:>12} {:>13}%".format(
        name, s["invoices"], s["gold_irn"], r["acc_when_gold"], s["acc_when_gold"],
        f"{s['match']}/{s['gold_irn']}", s["acc_when_in_ocr"],
    ))

print("\nFull pipeline IRN = 64-char hex script at the end (v3/regex/v1 unchanged).")
s_all = score(splits["all"], extract_irn_64)
print(
    f"TOTAL accuracy when gold IRN exists: {s_all['acc_when_gold']}%  "
    f"({s_all['match']}/{s_all['gold_irn']})"
)
print(f"TOTAL accuracy including blanks:     {s_all['acc_all']}%")
print(f"If gold IRN is present in OCR:       {s_all['acc_when_in_ocr']}%")
print("errors:", {k: s_all[k] for k in ("missing", "wrong", "false_positive", "both_blank")})

data_root: C:\Users\Prerana Bhalerao\OneDrive\Desktop\model train\training_export (2)\training_export
loading pdfplumber_train_batch_001.jsonl
loading pdfplumber_train_batch_002.jsonl
loading pdfplumber_train_batch_003.jsonl
loading pdfplumber_train_batch_004.jsonl
loading pdfplumber_train_batch_005.jsonl
loading pdfplumber_train_batch_006.jsonl
loading pdfplumber_train_batch_007.jsonl
loading pdfplumber_train_batch_008.jsonl
loading pdfplumber_train_batch_009.jsonl
loading pdfplumber_train_batch_010.jsonl
loading pdfplumber_train_batch_011.jsonl

split           n     gold    regex_acc   script_acc script_match  acc_if_in_ocr
--------------------------------------------------------------------------------------
val          5983     5597        81.9%       82.31%    4607/5597         99.31%
train       53752    51240        82.5%       84.69%  43397/51240         98.93%
all         59735    56837       82.44%       84.46%  48004/56837         98.97%

Full pipeline IRN = 64-char hex script at the end (v3/regex/v1 unchanged).
TOTAL accuracy when gold IRN exists: 84.46%  (48004/56837)
TOTAL accuracy including blanks:     84.36%
If gold IRN is present in OCR:       98.97%
errors: {'missing': 3606, 'wrong': 5227, 'false_positive': 508, 'both_blank': 2390}

In [14]:
# GSTIN validation + assignment script (run AFTER v3 + regex + v1)
# Does NOT change regex / v1 / v3. Overwrites vendor_gstin / customer_gstin at the end.
# Rules:
#  - find all valid 15-char GSTINs in OCR
#  - prefer Supplier/Seller/Vendor labels for vendor
#  - prefer Buyer/Bill To/Ship To/Customer labels for customer
#  - never allow vendor_gstin == customer_gstin if OCR has >= 2 GSTINs
#  - if ambiguous -> blank + needs_review

import re
from typing import Any

GSTIN_RE = re.compile(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]")
GSTIN_FULL = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")

VENDOR_LABEL_RE = re.compile(
    r"\b(?:"
    r"SUPPLIER(?:\s*GSTIN|\s*GST)?|"
    r"SELLER(?:\s*GSTIN|\s*GST)?|"
    r"VENDOR(?:\s*GSTIN|\s*GST)?|"
    r"FROM\s*GSTIN|"
    r"GSTIN\s*(?:OF\s*)?(?:SUPPLIER|SELLER|VENDOR)|"
    r"GST\s*(?:NO\.?|IN|NUMBER)?\s*(?:OF\s*)?(?:SUPPLIER|SELLER|VENDOR)|"
    r"GSTIN|GST\s*NO\.?|GST\s*NUMBER|GST\s*IN"
    r")\b",
    re.I,
)
CUSTOMER_LABEL_RE = re.compile(
    r"\b(?:"
    r"BUYER(?:\s*GSTIN|\s*GST)?|"
    r"CUSTOMER(?:\s*GSTIN|\s*GST)?|"
    r"BILL\s*TO|SHIP\s*TO|CONSIGNEE|TO\s*GSTIN|"
    r"GSTIN\s*(?:OF\s*)?(?:BUYER|CUSTOMER|BILL\s*TO|SHIP\s*TO)|"
    r"GST\s*(?:NO\.?|IN|NUMBER)?\s*(?:OF\s*)?(?:BUYER|CUSTOMER)"
    r")\b",
    re.I,
)
BLANK = {"", "none", "null", "nan", "n/a", "-", "na", "nil"}


def is_blank(v):
    return v is None or (isinstance(v, str) and v.strip().lower() in BLANK)


def norm_gstin(v):
    return re.sub(r"[^A-Z0-9]", "", str(v or "").upper())


def valid_gstin(v):
    g = norm_gstin(v)
    return bool(GSTIN_FULL.fullmatch(g)), g


def find_gstins_with_spans(ocr_text):
    text = ocr_text or ""
    compact_chars, compact_to_orig = [], []
    for i, ch in enumerate(text):
        if ch.isalnum():
            compact_chars.append(ch.upper())
            compact_to_orig.append(i)
    compact = "".join(compact_chars)
    found, seen = [], set()
    for m in GSTIN_RE.finditer(compact):
        g = m.group()
        if g in seen:
            continue
        seen.add(g)
        found.append((g, compact_to_orig[m.start()], compact_to_orig[m.end() - 1] + 1))
    return found


def _nearest_label_distance(pos, labels):
    best = None
    for m in labels:
        d = pos - m.end()
        if d < -40:
            continue
        score = abs(d) if d >= 0 else abs(d) + 20
        if best is None or score < best:
            best = score
    return best


def assign_gstins_from_ocr(ocr_text):
    text = ocr_text or ""
    gstins = find_gstins_with_spans(text)
    all_g = [g for g, _, _ in gstins]
    used = []
    vendor_labels = list(VENDOR_LABEL_RE.finditer(text))
    customer_labels = list(CUSTOMER_LABEL_RE.finditer(text))
    strong_customer = [m for m in customer_labels if re.search(r"BUYER|CUSTOMER|BILL\s*TO|SHIP\s*TO|CONSIGNEE", m.group(), re.I)]
    strong_vendor = [m for m in vendor_labels if re.search(r"SUPPLIER|SELLER|VENDOR|FROM\s*GSTIN", m.group(), re.I)]

    out = {
        "vendor_gstin": None,
        "customer_gstin": None,
        "needs_review": False,
        "reason": None,
        "all_gstins": all_g,
        "used": used,
    }
    if not gstins:
        out["needs_review"] = True
        out["reason"] = "no_gstin_in_ocr"
        used.append("gstin_script:none")
        return out

    if len(gstins) == 1:
        g, pos, _ = gstins[0]
        out["vendor_gstin"] = g
        out["needs_review"] = True
        out["reason"] = "only_one_gstin"
        used.append("gstin_script:single_vendor")
        return out

    def scores(pos):
        vd = _nearest_label_distance(pos, strong_vendor or vendor_labels)
        cd = _nearest_label_distance(pos, strong_customer or customer_labels)
        return (max(0.0, 1000.0 - vd) if vd is not None else 0.0,
                max(0.0, 1000.0 - cd) if cd is not None else 0.0)

    scored = []
    for g, pos, _ in gstins:
        v_s, c_s = scores(pos)
        idx = all_g.index(g)
        v_s += max(0.0, 5.0 - idx)
        c_s += idx * 1.5
        scored.append({"gstin": g, "pos": pos, "v": v_s, "c": c_s})

    by_v = sorted(scored, key=lambda x: (-x["v"], x["pos"]))
    vendor = by_v[0]["gstin"]
    remaining = [x for x in scored if x["gstin"] != vendor]
    by_c = sorted(remaining, key=lambda x: (-x["c"], -x["pos"]))
    customer = by_c[0]["gstin"]

    if by_v[0]["v"] < 50 and by_c[0]["c"] < 50:
        vendor, customer = all_g[0], all_g[1]
        used.append("gstin_script:order_fallback")
        out["needs_review"] = True
        out["reason"] = "ambiguous_label_scores"
    else:
        used.append("gstin_script:label_assign")

    if vendor == customer:
        other = next((g for g in all_g if g != vendor), None)
        if other:
            customer = other
            used.append("gstin_script:force_split")
            out["needs_review"] = True
            out["reason"] = "forced_split_equal"

    out["vendor_gstin"] = vendor
    out["customer_gstin"] = customer
    if out["vendor_gstin"] == out["customer_gstin"] and len(all_g) >= 2:
        out["customer_gstin"] = next(g for g in all_g if g != out["vendor_gstin"])
        used.append("gstin_script:final_split")
        out["needs_review"] = True
    if out["vendor_gstin"] is None or out["customer_gstin"] is None:
        out["needs_review"] = True
        out["reason"] = out["reason"] or "missing_party_gstin"
    return out


def apply_gstin_from_script(summary, ocr_text, used=None):
    out = dict(summary or {})
    used = used if used is not None else []
    a = assign_gstins_from_ocr(ocr_text)
    used.extend(a["used"])
    if a["vendor_gstin"]:
        if norm_gstin(out.get("vendor_gstin")) != a["vendor_gstin"]:
            used.append("script:vendor_gstin")
        out["vendor_gstin"] = a["vendor_gstin"]
    if a["customer_gstin"]:
        if norm_gstin(out.get("customer_gstin")) != a["customer_gstin"]:
            used.append("script:customer_gstin")
        out["customer_gstin"] = a["customer_gstin"]
    ok_v, vg = valid_gstin(out.get("vendor_gstin"))
    ok_c, cg = valid_gstin(out.get("customer_gstin"))
    if ok_v and ok_c and vg == cg and len(a["all_gstins"]) >= 2:
        out["customer_gstin"] = next(g for g in a["all_gstins"] if g != vg)
        used.append("script:force_unequal")
        a["needs_review"] = True
        a["reason"] = a["reason"] or "forced_unequal"
    return out, a["needs_review"], a["reason"]


# ---- demo ----
ocr_demo = """
HINDUSTAN PHARMA DISTRIBUTORS PVT LTD.
Supplier GSTIN : 29AACCD7912K1ZD
Bill To: ASTER HOSPITAL
Customer GSTIN : 29AAFCH9013A1ZV
Inv No: B159643
"""
demo = assign_gstins_from_ocr(ocr_demo)
print(demo)

# Use after pipeline:
#   result = run_pipeline(model, tokenizer, ocr_text)
#   s = result["final"]["invoice_summary"] if "final" in result else result["invoice_summary"]
#   s, needs_review, reason = apply_gstin_from_script(s, ocr_text, result.get("fallback_used", []))
#   print(s["vendor_gstin"], s["customer_gstin"], needs_review, reason)

{'vendor_gstin': '29AACCD7912K1ZD', 'customer_gstin': '29AAFCH9013A1ZV', 'needs_review': False, 'reason': None, 'all_gstins': ['29AACCD7912K1ZD', '29AAFCH9013A1ZV'], 'used': ['gstin_script:label_assign']}

In [ ]:
# ============================================================
# Train tiny GSTIN repair LoRA (vendor vs customer ONLY)
# Reuses same base: unsloth/Qwen2.5-1.5B-Instruct
# Saves to: /content/drive/MyDrive/invoice_adapters_all/invoice_lora_gstin_repair
# ============================================================

from pathlib import Path
from google.colab import drive
import json, re, random
import gc as py_gc
import torch
from datasets import Dataset
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only
from trl import SFTTrainer, SFTConfig

drive.mount("/content/drive", force_remount=False)

DATA_ROOT = Path("/content/drive/MyDrive/training_export/training_export")
OUT_DIR = Path("/content/drive/MyDrive/invoice_adapters_all/invoice_lora_gstin_repair")
OUT_DIR.mkdir(parents=True, exist_ok=True)

GSTIN_RE = re.compile(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]")
GSTIN_FULL = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")
BLANK = {"", "none", "null", "nan", "n/a", "-", "na", "nil"}
MAX_SEQ = 4096
SEED = 3407
MAX_TRAIN_ROWS = 8000  # raise if you want more


def norm_gstin(v):
    g = re.sub(r"[^A-Z0-9]", "", str(v or "").upper())
    return g if GSTIN_FULL.fullmatch(g) else ""


def find_gstins(ocr):
    compact = re.sub(r"[^A-Z0-9]", "", (ocr or "").upper())
    found, seen = [], set()
    for m in GSTIN_RE.finditer(compact):
        g = m.group()
        if g not in seen:
            seen.add(g)
            found.append(g)
    return found


def load_jsonl(path):
    rows = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


# ---- build clean GSTIN-only train set ----
train_files = sorted(DATA_ROOT.glob("pdfplumber_train_batch_*.jsonl"))
assert train_files, f"no train jsonl in {DATA_ROOT}"

examples = []
for path in train_files:
    for row in load_jsonl(path):
        ocr = (row.get("ocr_text") or "").strip()
        if len(ocr) < 200 or len(ocr) > 12000:
            continue
        gold = ((row.get("gemini_json") or {}).get("invoice_summary") or {})
        # NOTE: do NOT name this `gc` — that shadows the gc module
        gv, gcust = norm_gstin(gold.get("vendor_gstin")), norm_gstin(gold.get("customer_gstin"))
        found = find_gstins(ocr)
        # keep only clean, grounded, distinct pairs
        if not (gv and gcust and gv != gcust):
            continue
        if gv not in found or gcust not in found:
            continue
        if len(found) < 2:
            continue
        # shuffle candidate order so model learns role, not list order
        cands = found[:]
        random.Random(hash(gv + gcust) % (10**9)).shuffle(cands)
        user = (
            "Assign which GSTIN is vendor and which is customer from this invoice OCR.\n"
            "Use ONLY GSTINs from the candidate list. Reply with JSON only.\n\n"
            f"Candidates: {json.dumps(cands)}\n\n"
            f"OCR text:\n{ocr[:8000]}"
        )
        assistant = json.dumps(
            {"vendor_gstin": gv, "customer_gstin": gcust},
            ensure_ascii=False,
        )
        examples.append({
            "conversations": [
                {"role": "user", "content": user},
                {"role": "assistant", "content": assistant},
            ]
        })
        if len(examples) >= MAX_TRAIN_ROWS:
            break
    if len(examples) >= MAX_TRAIN_ROWS:
        break

random.Random(SEED).shuffle(examples)
print(f"clean GSTIN train examples: {len(examples)}")
assert len(examples) >= 200, "too few clean rows — check gold / paths"

# save dataset for reuse
ds_path = OUT_DIR / "gstin_train_examples.jsonl"
with ds_path.open("w", encoding="utf-8") as f:
    for ex in examples:
        f.write(json.dumps(ex, ensure_ascii=False) + "\n")
print("saved", ds_path)

# ---- load same base + new LoRA ----
for name in ("model", "tokenizer", "trainer"):
    if name in globals():
        del globals()[name]
py_gc.collect()
torch.cuda.empty_cache()

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=MAX_SEQ,
    dtype=None,
    load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=SEED,
)

def to_text(batch):
    texts = [
        tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False)
        for convo in batch["conversations"]
    ]
    return {"text": texts}

dataset = Dataset.from_list(examples).map(to_text, batched=True, remove_columns=["conversations"])

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    args=SFTConfig(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        warmup_steps=20,
        num_train_epochs=1,
        learning_rate=2e-4,
        fp16=not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps=10,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=SEED,
        output_dir=str(OUT_DIR / "checkpoints"),
        report_to="none",
        max_seq_length=MAX_SEQ,
        dataset_text_field="text",
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)

print("starting GSTIN repair training...")
trainer.train()
model.save_pretrained(str(OUT_DIR))
tokenizer.save_pretrained(str(OUT_DIR))
print("saved adapter to", OUT_DIR)

In [ ]:
# ============================================================
# Use gstin_repair AFTER GSTIN script (same loaded base)
# Requires: model/tokenizer already loaded with v3+v1, and assign_gstins_from_ocr
# ============================================================

from pathlib import Path
import json
import re

GSTIN_ADAPTER = "/content/drive/MyDrive/invoice_adapters_all/invoice_lora_gstin_repair"
assert Path(GSTIN_ADAPTER, "adapter_config.json").exists(), GSTIN_ADAPTER

# load once on the same model object
try:
    model.load_adapter(GSTIN_ADAPTER, adapter_name="gstin_repair")
except Exception:
    # already loaded
    pass

def run_gstin_repair(model, tokenizer, ocr_text, candidates):
    prompt = (
        "Assign which GSTIN is vendor and which is customer from this invoice OCR.\n"
        "Use ONLY GSTINs from the candidate list. Reply with JSON only.\n\n"
        f"Candidates: {json.dumps(candidates)}\n\n"
        f"OCR text:\n{(ocr_text or '')[:8000]}"
    )
    model.set_adapter("gstin_repair")
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}],
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=128, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    raw = raw.strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
    try:
        obj = json.loads(raw)
    except Exception:
        return None, raw
    return obj, raw


def apply_gstin_with_repair(summary, ocr_text, used=None):
    """Script finds GSTINs; tiny adapter assigns vendor vs customer when >=2."""
    used = used if used is not None else []
    out = dict(summary or {})
    a = assign_gstins_from_ocr(ocr_text)
    used.extend(a.get("used") or [])
    cands = a.get("all_gstins") or []

    if len(cands) < 2:
        # keep script result (single / none)
        if a.get("vendor_gstin"):
            out["vendor_gstin"] = a["vendor_gstin"]
        if a.get("customer_gstin"):
            out["customer_gstin"] = a["customer_gstin"]
        return out, a.get("needs_review", True), a.get("reason"), used

    obj, raw = run_gstin_repair(model, tokenizer, ocr_text, cands)
    if not isinstance(obj, dict):
        # fallback to script assignment
        out["vendor_gstin"] = a.get("vendor_gstin")
        out["customer_gstin"] = a.get("customer_gstin")
        used.append("gstin_repair:parse_fail")
        return out, True, "gstin_repair_parse_fail", used

    vg = norm_gstin(obj.get("vendor_gstin"))
    cg = norm_gstin(obj.get("customer_gstin"))
    # ground to candidates only
    if vg not in cands or cg not in cands or vg == cg:
        out["vendor_gstin"] = a.get("vendor_gstin")
        out["customer_gstin"] = a.get("customer_gstin")
        used.append("gstin_repair:ungrounded")
        return out, True, "gstin_repair_ungrounded", used

    out["vendor_gstin"] = vg
    out["customer_gstin"] = cg
    used.append("gstin_repair:assign")
    return out, False, None, used


# demo on one val row
val = Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl")
row = json.loads(next(val.open(encoding="utf-8")))
ocr = row["ocr_text"]
summary = ((row.get("gemini_json") or {}).get("invoice_summary") or {})
fixed, review, reason, used = apply_gstin_with_repair({}, ocr, [])
print("gold vendor/customer:", norm_gstin(summary.get("vendor_gstin")), norm_gstin(summary.get("customer_gstin")))
print("pred vendor/customer:", fixed.get("vendor_gstin"), fixed.get("customer_gstin"))
print("review/reason/used:", review, reason, used)

In [15]:
# Check GSTIN script is working: demos + val accuracy
# Run AFTER the GSTIN script cell (assign_gstins_from_ocr must exist)

import json
import re
from collections import Counter
from pathlib import Path

assert "assign_gstins_from_ocr" in dir(), "Run the GSTIN script cell first"

# ---------- paths ----------
VAL_CANDIDATES = [
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl"),
    Path("/content/drive/MyDrive/training_export/pdfplumber_val.jsonl"),
]
LIMIT = 200  # set None for full val

val_path = next((p for p in VAL_CANDIDATES if p.exists()), None)
if val_path is None:
    hits = list(Path("/content/drive/MyDrive").rglob("pdfplumber_val.jsonl"))
    assert hits, "pdfplumber_val.jsonl not found — mount Drive"
    val_path = hits[0]
print("VAL_PATH =", val_path)

BLANK = {"", "none", "null", "nan", "n/a", "-", "na", "nil"}
GSTIN_FULL = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")


def is_blank(v):
    return v is None or (isinstance(v, str) and v.strip().lower() in BLANK)


def norm_gstin(v):
    g = re.sub(r"[^A-Z0-9]", "", str(v or "").upper())
    return g if GSTIN_FULL.fullmatch(g) else ""


def gold_pair(row):
    s = ((row.get("gemini_json") or {}).get("invoice_summary") or {})
    return norm_gstin(s.get("vendor_gstin")), norm_gstin(s.get("customer_gstin"))


# ========== 1) DEMO CHECKS ==========
print("\n===== DEMO CHECKS =====")
demos = [
    (
        "label_assign",
        """
        Supplier GSTIN : 29AACCD7912K1ZD
        Bill To: ASTER
        Customer GSTIN : 29AAFCH9013A1ZV
        """,
        "29AACCD7912K1ZD",
        "29AAFCH9013A1ZV",
    ),
    (
        "force_split_equal_case",
        """
        GST : 29AACCD7912K1ZD
        GST NO. : 29AAFCH9013A1ZV
        Inv No B159643
        """,
        "29AACCD7912K1ZD",  # first ~ vendor in order fallback
        "29AAFCH9013A1ZV",
    ),
    (
        "single_gstin",
        "Only one GSTIN 29AACCD7912K1ZD on invoice",
        "29AACCD7912K1ZD",
        None,
    ),
    (
        "no_gstin",
        "TAX INVOICE no gst here at all " + ("X" * 50),
        None,
        None,
    ),
]

demo_pass = 0
for name, ocr, exp_v, exp_c in demos:
    a = assign_gstins_from_ocr(ocr)
    ok_v = (a["vendor_gstin"] == exp_v) if exp_v else (a["vendor_gstin"] in (None, exp_v))
    ok_c = (a["customer_gstin"] == exp_c) if exp_c else (a["customer_gstin"] in (None, exp_c))
    # single/no gstin: mainly check needs_review
    if name in {"single_gstin", "no_gstin"}:
        ok = a["needs_review"] is True
    else:
        ok = ok_v and ok_c and (a["vendor_gstin"] != a["customer_gstin"])
    demo_pass += int(ok)
    print(f"{'PASS' if ok else 'FAIL'} | {name}")
    print(f"  got vendor={a['vendor_gstin']} customer={a['customer_gstin']} review={a['needs_review']} reason={a['reason']}")

print(f"demos: {demo_pass}/{len(demos)} passed")

# ========== 2) VAL SCORE ==========
print("\n===== VAL SCORE =====")
rows = []
with val_path.open(encoding="utf-8") as f:
    for line in f:
        if LIMIT is not None and len(rows) >= LIMIT:
            break
        rec = json.loads(line)
        if rec.get("ocr_text"):
            rows.append(rec)
print(f"scoring {len(rows)} invoices")

c = Counter()
for row in rows:
    ocr = row.get("ocr_text") or ""
    gv, gcust = gold_pair(row)
    a = assign_gstins_from_ocr(ocr)
    pv, pc = a["vendor_gstin"], a["customer_gstin"]
    all_g = a["all_gstins"]

    c["n"] += 1
    if a["needs_review"]:
        c["needs_review"] += 1

    # hard rule: never equal when OCR has >=2
    if len(all_g) >= 2 and pv and pc and pv == pc:
        c["equal_fail"] += 1

    # score only when gold has two distinct valid GSTINs that appear in OCR
    gold_usable = bool(gv and gcust and gv != gcust and gv in all_g and gcust in all_g)
    if not gold_usable:
        c["skip_gold"] += 1
        continue

    c["scored"] += 1
    if pv == gv and pc == gc:
        c["both_ok"] += 1
    elif pv == gcust and pc == gv:
        c["swapped"] += 1
    elif pv == gv or pc == gcust:
        c["partial"] += 1
    else:
        c["wrong"] += 1

n = c["n"] or 1
scored = c["scored"] or 1
print("\n--- summary ---")
print(f"invoices              : {c['n']}")
print(f"needs_review rate     : {100*c['needs_review']/n:.2f}%")
print(f"equal_fail (must ~0%) : {c['equal_fail']}  ({100*c['equal_fail']/n:.2f}%)")
print(f"gold-usable scored    : {c['scored']}  (skipped bad/missing gold: {c['skip_gold']})")
print(f"both correct          : {c['both_ok']}  ({100*c['both_ok']/scored:.2f}%)")
print(f"swapped               : {c['swapped']}  ({100*c['swapped']/scored:.2f}%)")
print(f"partial               : {c['partial']}  ({100*c['partial']/scored:.2f}%)")
print(f"wrong                 : {c['wrong']}  ({100*c['wrong']/scored:.2f}%)")

print("\n===== VERDICT =====")
if c["equal_fail"] == 0 and c["both_ok"] / scored >= 0.70:
    print("PASS: script looks healthy (no equal fails, both-correct >= 70% on usable gold)")
elif c["equal_fail"] == 0:
    print("PARTIAL: equal-split OK, but accuracy still low → hard layouts remain (tiny GSTIN model next)")
else:
    print("FAIL: still producing equal vendor/customer GSTINs — fix script before training")

VAL_PATH = /content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl

===== DEMO CHECKS =====
PASS | label_assign
  got vendor=29AACCD7912K1ZD customer=29AAFCH9013A1ZV review=False reason=None
FAIL | force_split_equal_case
  got vendor=29AAFCH9013A1ZV customer=29AACCD7912K1ZD review=False reason=None
PASS | single_gstin
  got vendor=29AACCD7912K1ZD customer=None review=True reason=only_one_gstin
PASS | no_gstin
  got vendor=None customer=None review=True reason=no_gstin_in_ocr
demos: 3/4 passed

===== VAL SCORE =====
scoring 200 invoices

--- summary ---
invoices              : 200
needs_review rate     : 6.50%
equal_fail (must ~0%) : 0  (0.00%)
gold-usable scored    : 70  (skipped bad/missing gold: 130)
both correct          : 22  (31.43%)
swapped               : 48  (68.57%)
partial               : 0  (0.00%)
wrong                 : 0  (0.00%)

===== VERDICT =====
PARTIAL: equal-split OK, but accuracy still low → hard layouts remain (tiny GSTIN model next)

In [23]:
# ============================================================
# PASTE/RUN THIS NEW CELL (do NOT re-run the old broken train cell)
# Bug was: filter used `gc` (module) instead of `gcust` → 0 examples
# ============================================================

from pathlib import Path
from google.colab import drive
import json, re, random
import gc as py_gc
import torch
from datasets import Dataset
from unsloth import FastLanguageModel, is_bfloat16_supported
from unsloth.chat_templates import train_on_responses_only
from trl import SFTTrainer, SFTConfig

drive.mount("/content/drive", force_remount=False)

# find train files automatically
DATA_ROOT = None
for root in [
    Path("/content/drive/MyDrive/training_export/training_export"),
    Path("/content/drive/MyDrive/training_export"),
]:
    files = list(root.glob("pdfplumber_train_batch_*.jsonl"))
    if files:
        DATA_ROOT = root
        break
if DATA_ROOT is None:
    hits = list(Path("/content/drive/MyDrive").rglob("pdfplumber_train_batch_001.jsonl"))
    assert hits, "train jsonl not found"
    DATA_ROOT = hits[0].parent

OUT_DIR = Path("/content/drive/MyDrive/invoice_adapters_all/invoice_lora_gstin_repair")
OUT_DIR.mkdir(parents=True, exist_ok=True)
train_files = sorted(DATA_ROOT.glob("pdfplumber_train_batch_*.jsonl"))
print("DATA_ROOT =", DATA_ROOT)
print("train files =", len(train_files))
assert train_files, DATA_ROOT

GSTIN_RE = re.compile(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]")
GSTIN_FULL = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")
MAX_SEQ = 4096
SEED = 3407
MAX_TRAIN_ROWS = 8000

def norm_gstin(v):
    g = re.sub(r"[^A-Z0-9]", "", str(v or "").upper())
    return g if GSTIN_FULL.fullmatch(g) else ""

def find_gstins(ocr):
    compact = re.sub(r"[^A-Z0-9]", "", (ocr or "").upper())
    out, seen = [], set()
    for m in GSTIN_RE.finditer(compact):
        g = m.group()
        if g not in seen:
            seen.add(g)
            out.append(g)
    return out

def load_jsonl(path):
    rows = []
    with path.open(encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows

examples = []
stats = {"seen": 0, "kept": 0, "bad_len": 0, "bad_gold": 0, "not_in_ocr": 0}

for path in train_files:
    for row in load_jsonl(path):
        stats["seen"] += 1
        ocr = (row.get("ocr_text") or "").strip()
        if len(ocr) < 200 or len(ocr) > 12000:
            stats["bad_len"] += 1
            continue
        gold = ((row.get("gemini_json") or {}).get("invoice_summary") or {})
        gv = norm_gstin(gold.get("vendor_gstin"))
        gcust = norm_gstin(gold.get("customer_gstin"))  # NEVER use name `gc`
        found = find_gstins(ocr)

        # CRITICAL: use gcust here, NOT gc
        if not (gv and gcust and gv != gcust):
            stats["bad_gold"] += 1
            continue
        if (gv not in found) or (gcust not in found) or (len(found) < 2):
            stats["not_in_ocr"] += 1
            continue

        cands = found[:]
        random.Random(hash(gv + gcust) % (10**9)).shuffle(cands)
        user = (
            "Assign which GSTIN is vendor and which is customer from this invoice OCR.\n"
            "Use ONLY GSTINs from the candidate list. Reply with JSON only.\n\n"
            f"Candidates: {json.dumps(cands)}\n\nOCR text:\n{ocr[:8000]}"
        )
        assistant = json.dumps({"vendor_gstin": gv, "customer_gstin": gcust}, ensure_ascii=False)
        examples.append({"conversations": [
            {"role": "user", "content": user},
            {"role": "assistant", "content": assistant},
        ]})
        stats["kept"] += 1
        if len(examples) >= MAX_TRAIN_ROWS:
            break
    if len(examples) >= MAX_TRAIN_ROWS:
        break

random.Random(SEED).shuffle(examples)
print("filter stats:", stats)
print("clean GSTIN train examples:", len(examples))
assert len(examples) >= 200, stats

# save dataset
with (OUT_DIR / "gstin_train_examples.jsonl").open("w", encoding="utf-8") as f:
    for ex in examples:
        f.write(json.dumps(ex, ensure_ascii=False) + "\n")

# train
for name in ("model", "tokenizer", "trainer"):
    if name in globals():
        del globals()[name]
py_gc.collect()
torch.cuda.empty_cache()

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=MAX_SEQ, dtype=None, load_in_4bit=True,
)
model = FastLanguageModel.get_peft_model(
    model, r=16,
    target_modules=["q_proj","k_proj","v_proj","o_proj","gate_proj","up_proj","down_proj"],
    lora_alpha=16, lora_dropout=0, bias="none",
    use_gradient_checkpointing="unsloth", random_state=SEED,
)

def to_text(batch):
    return {"text": [
        tokenizer.apply_chat_template(c, tokenize=False, add_generation_prompt=False)
        for c in batch["conversations"]
    ]}

dataset = Dataset.from_list(examples).map(to_text, batched=True, remove_columns=["conversations"])
trainer = SFTTrainer(
    model=model, tokenizer=tokenizer, train_dataset=dataset,
    args=SFTConfig(
        per_device_train_batch_size=2, gradient_accumulation_steps=4,
        warmup_steps=20, num_train_epochs=1, learning_rate=2e-4,
        fp16=not is_bfloat16_supported(), bf16=is_bfloat16_supported(),
        logging_steps=10, optim="adamw_8bit", weight_decay=0.01,
        lr_scheduler_type="linear", seed=SEED,
        output_dir=str(OUT_DIR / "checkpoints"), report_to="none",
        max_seq_length=MAX_SEQ, dataset_text_field="text",
    ),
)
trainer = train_on_responses_only(
    trainer,
    instruction_part="<|im_start|>user\n",
    response_part="<|im_start|>assistant\n",
)
print("starting GSTIN repair training...")
trainer.train()
model.save_pretrained(str(OUT_DIR))
tokenizer.save_pretrained(str(OUT_DIR))
print("saved", OUT_DIR)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
DATA_ROOT = /content/drive/MyDrive/training_export/training_export
train files = 11
filter stats: {'seen': 14891, 'kept': 8000, 'bad_len': 675, 'bad_gold': 6216, 'not_in_ocr': 0}
clean GSTIN train examples: 8000
==((====))==  Unsloth 2026.9.6: Fast Qwen2 patching. Transformers: 4.56.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.34. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Map:   0%|          | 0/8000 [00:00<?, ? examples/s]

Unsloth: Tokenizing ["text"] (num_proc=2):   0%|          | 0/8000 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

Map (num_proc=2):   0%|          | 0/8000 [00:00<?, ? examples/s]

Filter (num_proc=2):   0%|          | 0/8000 [00:00<?, ? examples/s]

Unsloth: Removed 1584 out of 8000 samples from train_dataset where all labels were -100 (no response marker found, usually truncation). This prevents NaN loss during training.
starting GSTIN repair training...

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 6,416 | Num Epochs = 1 | Total steps = 802
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 18,464,768 of 1,562,179,072 (1.18% trained)

Unsloth: Will smartly offload gradients to save VRAM!

/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:2825: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:2825: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:2825: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  return original(name)
/usr/local/lib/python3.13/dist-packages/unsloth/import_fixes.py:2825: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  return original(name)

Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.

saved /content/drive/MyDrive/invoice_adapters_all/invoice_lora_gstin_repair

In [4]:
# Cell 0 — install (run once after Runtime restart)
import os, re

if "COLAB_" not in "".join(os.environ.keys()):
    print("Not Colab")
else:
    !pip install -q unsloth
    !pip install -q --no-deps "trl<0.20.0" peft accelerate bitsandbytes
    print("unsloth install done")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 107.4 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 63.4 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 47.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.8/73.8 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 156.2 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 38.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 89.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 100.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 127.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.9/216.9 kB 23.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.7/119.7 kB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 24.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.7/146.7 kB 18.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 124.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 124.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.1/225.1 kB 25.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.12.0 requires fsspec==2025.12.0, but you have fsspec 2025.9.0 which is incompatible.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 376.2/376.2 kB 31.5 MB/s eta 0:00:00
unsloth install done

In [1]:
# ============================================================
# QUICK ACCURACY — 20 invoices only
# Pipeline: v3 -> regex -> v1 -> IRN script -> GSTIN script -> gstin_repair
# ============================================================

from pathlib import Path
from google.colab import drive
import json, re, gc as py_gc
from copy import deepcopy
import torch
from unsloth import FastLanguageModel
from peft import PeftModel
from safetensors import safe_open

drive.mount("/content/drive", force_remount=False)

LIMIT = 20
MAX_PROMPT_TOKENS = 6000
MAX_SEQ = 8192

V3_PATH = "/content/drive/MyDrive/invoice_adapters_all/invoice_lora_v3"
V1_PATH = "/content/drive/MyDrive/invoice_adapters_all/invoice_lora"
GSTIN_PATH = "/content/drive/MyDrive/invoice_adapters_all/invoice_lora_gstin_repair"

VAL_CANDIDATES = [
    Path("/content/drive/MyDrive/training_export/training_export/pdfplumber_val.jsonl"),
    Path("/content/drive/MyDrive/training_export/pdfplumber_val.jsonl"),
]
val_path = next((p for p in VAL_CANDIDATES if p.exists()), None)
if val_path is None:
    hits = list(Path("/content/drive/MyDrive").rglob("pdfplumber_val.jsonl"))
    assert hits, "val jsonl not found"
    val_path = hits[0]
print("VAL_PATH =", val_path)

SCORE_FIELDS = [
    "invoice_no", "invoice_date", "vendor", "customer",
    "vendor_gstin", "customer_gstin", "tax", "total", "irn",
]
STRICT_FIELDS = ["invoice_no", "vendor_gstin", "customer_gstin", "tax", "total"]
HEADER_FIELDS = ["vendor", "vendor_gstin", "tax", "irn"]
BLANK = {"", "none", "null", "nan", "n/a", "-", "na", "nil"}
HEX = set("0123456789abcdefABCDEF")
GSTIN_RE = re.compile(r"[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]")
GSTIN_FULL = re.compile(r"^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][A-Z0-9]Z[A-Z0-9]$")

INSTRUCTION = (
    "Extract this invoice from the OCR text. "
    "Reply with JSON only, with keys invoice_summary and line_items."
)

def is_blank(v):
    return v is None or (isinstance(v, str) and v.strip().lower() in BLANK)

def norm_gstin(v):
    g = re.sub(r"[^A-Z0-9]", "", str(v or "").upper())
    return g if GSTIN_FULL.fullmatch(g) else ""

def valid_gstin(v):
    g = norm_gstin(v)
    return bool(g), g

def norm_field(name, v):
    if is_blank(v):
        return ""
    s = str(v).strip()
    if name in {"vendor_gstin", "customer_gstin"}:
        return norm_gstin(s)
    if name in {"tax", "total"}:
        return re.sub(r"[, ]", "", s)
    if name == "irn":
        return "".join(ch.lower() for ch in s if ch in HEX)
    return re.sub(r"\s+", " ", s.upper())

def parse_json(text):
    text = (text or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    try:
        return json.loads(text)
    except Exception:
        return None

def extract_irn_64(ocr_text):
    text = ocr_text or ""
    m = re.search(r"[a-fA-F0-9]{64}", text)
    if m:
        return m.group().lower()
    gapped = re.search(r"[a-fA-F0-9](?:[\s\-]*[a-fA-F0-9]){63}", text)
    if gapped:
        return "".join(ch.lower() for ch in gapped.group() if ch in HEX)
    return None

def find_gstins(ocr):
    compact = re.sub(r"[^A-Z0-9]", "", (ocr or "").upper())
    out, seen = [], set()
    for m in GSTIN_RE.finditer(compact):
        g = m.group()
        if g not in seen:
            seen.add(g)
            out.append(g)
    return out

def regex_fill(summary, ocr, used):
    summary = dict(summary or {})
    found = find_gstins(ocr)
    ok, _ = valid_gstin(summary.get("vendor_gstin"))
    if (not ok) and found:
        summary["vendor_gstin"] = found[0]
        used.append("regex:vendor_gstin")
    ok_c, _ = valid_gstin(summary.get("customer_gstin"))
    if (not ok_c) and len(found) >= 2:
        summary["customer_gstin"] = found[1]
        used.append("regex:customer_gstin")
    if is_blank(summary.get("irn")):
        irn = extract_irn_64(ocr)
        if irn:
            summary["irn"] = irn
            used.append("regex:irn")
    return summary

def needs_header_fallback(summary):
    summary = summary or {}
    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(summary.get(k))
            if not ok:
                return True
        elif is_blank(summary.get(k)):
            return True
    return False

def merge_header_from_v1(base_obj, v1_obj, used):
    out = deepcopy(base_obj) if isinstance(base_obj, dict) else {"invoice_summary": {}, "line_items": None}
    s = out.setdefault("invoice_summary", {})
    s1 = ((v1_obj or {}).get("invoice_summary") or {}) if isinstance(v1_obj, dict) else {}
    for k in HEADER_FIELDS:
        if k == "vendor_gstin":
            ok, _ = valid_gstin(s.get(k))
            ok1, g1 = valid_gstin(s1.get(k))
            if (not ok) and ok1:
                s[k] = g1
                used.append(f"v1:{k}")
        else:
            if is_blank(s.get(k)) and not is_blank(s1.get(k)):
                s[k] = s1[k]
                used.append(f"v1:{k}")
    out["invoice_summary"] = s
    return out

def generate(model, tokenizer, ocr_text, max_new_tokens=2048):
    prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr_text.strip()
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}], tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=max_new_tokens, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True)
    return raw, parse_json(raw)

def run_gstin_repair(model, tokenizer, ocr_text, candidates):
    prompt = (
        "Assign which GSTIN is vendor and which is customer from this invoice OCR.\n"
        "Use ONLY GSTINs from the candidate list. Reply with JSON only.\n\n"
        f"Candidates: {json.dumps(candidates)}\n\nOCR text:\n{(ocr_text or '')[:8000]}"
    )
    model.set_adapter("gstin_repair")
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}], tokenize=False, add_generation_prompt=True
    )
    inputs = tokenizer(text, return_tensors="pt").to(model.device)
    out = model.generate(**inputs, max_new_tokens=128, do_sample=False, use_cache=True)
    raw = tokenizer.decode(out[0][inputs["input_ids"].shape[-1]:], skip_special_tokens=True).strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)
    return parse_json(raw)

def run_full_pipeline(model, tokenizer, ocr_text):
    used = []
    model.set_adapter("v3")
    _, obj = generate(model, tokenizer, ocr_text)
    if not isinstance(obj, dict):
        obj = {"invoice_summary": {}, "line_items": None}
    summary = regex_fill(dict(obj.get("invoice_summary") or {}), ocr_text, used)

    irn = extract_irn_64(ocr_text)
    if irn:
        summary["irn"] = irn
        used.append("script:irn")
    obj["invoice_summary"] = summary

    if needs_header_fallback(summary):
        model.set_adapter("v1")
        _, obj_v1 = generate(model, tokenizer, ocr_text)
        obj = merge_header_from_v1(obj, obj_v1, used)
        summary = regex_fill(dict(obj.get("invoice_summary") or {}), ocr_text, used)
        if irn:
            summary["irn"] = irn
        obj["invoice_summary"] = summary

    cands = find_gstins(ocr_text)
    if len(cands) >= 2 and Path(GSTIN_PATH, "adapter_config.json").exists():
        repaired = run_gstin_repair(model, tokenizer, ocr_text, cands)
        if isinstance(repaired, dict):
            vg, cg = norm_gstin(repaired.get("vendor_gstin")), norm_gstin(repaired.get("customer_gstin"))
            if vg in cands and cg in cands and vg != cg:
                summary["vendor_gstin"] = vg
                summary["customer_gstin"] = cg
                used.append("gstin_repair:assign")
            else:
                used.append("gstin_repair:ungrounded")
        else:
            used.append("gstin_repair:parse_fail")
    obj["invoice_summary"] = summary
    return obj, used

def line_count(obj):
    if not isinstance(obj, dict):
        return None
    li = obj.get("line_items")
    if isinstance(li, dict) and isinstance(li.get("items"), list):
        return len(li["items"])
    if isinstance(li, list):
        return len(li)
    return None

def _count_adapter_keys(path):
    with safe_open(str(Path(path) / "adapter_model.safetensors"), framework="pt") as f:
        return len(list(f.keys()))

def _present_keys(model, adapter_name):
    return [
        k for k in model.state_dict()
        if f"lora_A.{adapter_name}.weight" in k or f"lora_B.{adapter_name}.weight" in k
    ]

def load_adapters_present(model, adapters):
    loaded, first = [], True
    for name, path in adapters:
        path = Path(path)
        assert (path / "adapter_config.json").exists(), path
        assert (path / "adapter_model.safetensors").exists(), path
        n_file = _count_adapter_keys(path)
        if first:
            model = PeftModel.from_pretrained(model, str(path), adapter_name=name)
            first = False
        else:
            if hasattr(model, "peft_config") and name in model.peft_config:
                try:
                    model.delete_adapter(name)
                except Exception:
                    pass
            model.load_adapter(str(path), adapter_name=name)
        keys = _present_keys(model, name)
        assert name in model.peft_config and len(keys) == n_file, (name, len(keys), n_file)
        print(f"PRESENT {name}: {len(keys)}/{n_file}")
        loaded.append(name)
    model.set_adapter(loaded[0])
    return model, loaded

# ---- load ----
for name in ("model", "tokenizer"):
    if name in globals():
        del globals()[name]
py_gc.collect(); torch.cuda.empty_cache()

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/Qwen2.5-1.5B-Instruct",
    max_seq_length=MAX_SEQ, dtype=None, load_in_4bit=True,
)
adapters = [("v3", V3_PATH), ("v1", V1_PATH)]
if Path(GSTIN_PATH, "adapter_config.json").exists():
    adapters.append(("gstin_repair", GSTIN_PATH))
model, loaded_names = load_adapters_present(model, adapters)
FastLanguageModel.for_inference(model)
print("loaded OK:", ", ".join(loaded_names))

# ---- score 20 ----
rows = []
with val_path.open(encoding="utf-8") as f:
    for line in f:
        if len(rows) >= LIMIT:
            break
        rec = json.loads(line)
        if rec.get("ocr_text"):
            rows.append(rec)
print(f"scoring {len(rows)} invoices (LIMIT={LIMIT})")

stats = {k: {"n": 0, "ok": 0, "missing": 0, "wrong": 0} for k in SCORE_FIELDS + ["line_count"]}
strict_ok = skipped_long = invoice_fail = scored = 0

for i, row in enumerate(rows, 1):
    ocr = (row.get("ocr_text") or "").strip()
    prompt = INSTRUCTION + "\n\nOCR text:\n" + ocr
    text = tokenizer.apply_chat_template(
        [{"role": "user", "content": prompt}], tokenize=False, add_generation_prompt=True
    )
    ntok = len(tokenizer(text, add_special_tokens=False)["input_ids"])
    if ntok > MAX_PROMPT_TOKENS:
        skipped_long += 1
        continue

    pred, used = run_full_pipeline(model, tokenizer, ocr)
    ps = dict(pred.get("invoice_summary") or {})
    gs = ((row.get("gemini_json") or {}).get("invoice_summary") or {})

    field_fail = False
    for field in SCORE_FIELDS:
        g, p = norm_field(field, gs.get(field)), norm_field(field, ps.get(field))
        stats[field]["n"] += 1
        if is_blank(ps.get(field)):
            stats[field]["missing"] += 1
            field_fail = True
        elif p == g:
            stats[field]["ok"] += 1
        else:
            stats[field]["wrong"] += 1
            field_fail = True

    gc_, pc_ = line_count(row.get("gemini_json") or {}), line_count(pred)
    stats["line_count"]["n"] += 1
    if pc_ is None:
        stats["line_count"]["missing"] += 1
        field_fail = True
    elif pc_ == gc_:
        stats["line_count"]["ok"] += 1
    else:
        stats["line_count"]["wrong"] += 1
        field_fail = True

    if all((not is_blank(ps.get(k))) and norm_field(k, ps.get(k)) == norm_field(k, gs.get(k)) for k in STRICT_FIELDS):
        strict_ok += 1
    if field_fail:
        invoice_fail += 1
    scored += 1
    print(f"scored {i}/{len(rows)}")

print("\n" + "=" * 92)
print(f"{'field':<18} {'n':>6} {'ok':>6} {'missing':>8} {'wrong':>7} {'accuracy':>10} {'fail_rate':>10}")
print("-" * 92)
total_ok = total_n = total_fail = 0
for field, s in stats.items():
    n = s["n"] or 1
    acc = 100 * s["ok"] / n
    fail = 100 * (s["missing"] + s["wrong"]) / n
    total_ok += s["ok"]; total_n += s["n"]; total_fail += s["missing"] + s["wrong"]
    print(f"{field:<18} {s['n']:>6} {s['ok']:>6} {s['missing']:>8} {s['wrong']:>7} {acc:>9.2f}% {fail:>9.2f}%")
print("-" * 92)
print(f"{'ALL FIELDS':<18} {total_n:>6} {total_ok:>6} {'':>8} {'':>7} {100*total_ok/total_n if total_n else 0:>9.2f}% {100*total_fail/total_n if total_n else 0:>9.2f}%")
print("=" * 92)
print(f"invoices scored:    {scored}")
print(f"skipped too long:   {skipped_long}")
print(f"strict-field pass:  {strict_ok}/{scored} ({100*strict_ok/scored if scored else 0:.2f}%)")
print(f"invoice fail rate:  {invoice_fail}/{scored} ({100*invoice_fail/scored if scored else 0:.2f}%)")

ModuleNotFoundError: No module named 'unsloth'